import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt-BR' | 'en-US' | 'es-ES' | 'fr-FR';

interface Translations {
  [key: string]: {
    [K in Language]: string;
  };
}

export const translations: Translations = {
  weekly: { 'pt-BR': 'Semanal', 'en-US': 'Weekly', 'es-ES': 'Semanal', 'fr-FR': 'Hebdomadaire' },
  biweekly: { 'pt-BR': 'Quinzenal', 'en-US': 'Bi-weekly', 'es-ES': 'Quincenal', 'fr-FR': 'Bimensuel' },
  monthly: { 'pt-BR': 'Mensal', 'en-US': 'Monthly', 'es-ES': 'Mensual', 'fr-FR': 'Mensuel' },
  yearly: { 'pt-BR': 'Anual', 'en-US': 'Yearly', 'es-ES': 'Anual', 'fr-FR': 'Annuel' },
  paymentDate: { 'pt-BR': 'Data do Pagamento', 'en-US': 'Payment Date', 'es-ES': 'Fecha de Pago', 'fr-FR': 'Date de Paiement' },
  nextPayment: { 'pt-BR': 'Próximo Pagamento', 'en-US': 'Next Payment', 'es-ES': 'Próximo Pago', 'fr-FR': 'Prochain Paiement' },
  value: { 'pt-BR': 'Valor', 'en-US': 'Value', 'es-ES': 'Valor', 'fr-FR': 'Valeur' },
  none: { 'pt-BR': 'Nenhuma', 'en-US': 'None', 'es-ES': 'Ninguna', 'fr-FR': 'Aucune' },
  frequencyTooltip: { 
    'pt-BR': 'A partir da data do pagamento, o próximo será:\n• Semanal: +7 dias\n• Quinzenal: +15 dias\n• Mensal: +1 mês (ajusta para o último dia se o dia não existir)\n• Anual: +1 ano',
    'en-US': 'From the payment date, the next will be:\n• Weekly: +7 days\n• Bi-weekly: +15 days\n• Monthly: +1 month (adjusts to last day if date doesn\'t exist)\n• Yearly: +1 year',
    'es-ES': 'Desde la fecha de pago, la próxima será:\n• Semanal: +7 días\n• Quincenal: +15 días\n• Mensual: +1 mes (ajusta al último día si el día no existe)\n• Anual: +1 año',
    'fr-FR': 'À partir de la date de paiement, le prochain sera:\n• Hebdomodaire: +7 jours\n• Bimensuel: +15 jours\n• Mensuel: +1 mois (ajusté au dernier jour si le jour n\'existe pas)\n• Annuel: +1 an'
  },
  paidThisMonth: { 'pt-BR': 'Conta já paga este período?', 'en-US': 'Bill already paid this period?', 'es-ES': '¿Cuenta ya pagada este período?', 'fr-FR': 'Compte déjà payé cette période?' },
  select: { 'pt-BR': 'Selecione', 'en-US': 'Select', 'es-ES': 'Seleccionar', 'fr-FR': 'Sélectionner' },
  dashboard: { 'pt-BR': 'Painel', 'en-US': 'Dashboard', 'es-ES': 'Panel', 'fr-FR': 'Tableau de bord' },
  reports: { 'pt-BR': 'Relatórios', 'en-US': 'Reports', 'es-ES': 'Informes', 'fr-FR': 'Rapports' },
  add: { 'pt-BR': 'Adicionar', 'en-US': 'Add', 'es-ES': 'Añadir', 'fr-FR': 'Ajouter' },
  settings: { 'pt-BR': 'Ajustes', 'en-US': 'Settings', 'es-ES': 'Ajustes', 'fr-FR': 'Paramètres' },
  calculator: { 'pt-BR': 'Calculadora Flex', 'en-US': 'Flex Calculator', 'es-ES': 'Calculadora Flex', 'fr-FR': 'Calculatrice Flex' },
  realProfit: { 'pt-BR': 'Lucro', 'en-US': 'Profit', 'es-ES': 'Beneficio', 'fr-FR': 'Bénéfice' },
  incomeTax: { 'pt-BR': 'Imposto de Renda', 'en-US': 'Income Tax', 'es-ES': 'Impuesto de Renta', 'fr-FR': 'Impôt sur le Revenu' },
  incomeTaxInfo: { 
    'pt-BR': 'Base de cálculo tributável de 60% sobre os ganhos brutos do ano, conforme legislação para motoristas.', 
    'en-US': '60% taxable income base on gross earnings of the year, according to legislation for drivers.', 
    'es-ES': 'Base imponible del 60% sobre los ingresos brutos del año, según la legislación para conductores.', 
    'fr-FR': 'Base d\'imposition de 60 % sur les gains bruts de l\'année, conformément à la législation pour les chauffeurs.' 
  },
  grossEarnings: { 'pt-BR': 'Ganhos Brutos', 'en-US': 'Gross Earnings', 'es-ES': 'Ingresos Brutos', 'fr-FR': 'Gains Bruts' },
  totalExpenses: { 'pt-BR': 'Gastos Totais', 'en-US': 'Total Expenses', 'es-ES': 'Gastos Totales', 'fr-FR': 'Dépenses Totales' },
  totalProfit: { 'pt-BR': 'Lucro Total', 'en-US': 'Total Profit', 'es-ES': 'Beneficio Total', 'fr-FR': 'Bénéfice Total' },
  totalEarnings: { 'pt-BR': 'Ganhos Totais', 'en-US': 'Total Earnings', 'es-ES': 'Ingresos Totales', 'fr-FR': 'Gains Totaux' },
  trips: { 'pt-BR': 'Viagens', 'en-US': 'Trips', 'es-ES': 'Viajes', 'fr-FR': 'Voyages' },
  hours: { 'pt-BR': 'Horas', 'en-US': 'Hours', 'es-ES': 'Horas', 'fr-FR': 'Heures' },
  km: { 'pt-BR': 'KM', 'en-US': 'KM', 'es-ES': 'KM', 'fr-FR': 'KM' },
  goalProgress: { 'pt-BR': 'Progresso da Meta', 'en-US': 'Goal Progress', 'es-ES': 'Progreso de la Meta', 'fr-FR': 'Progression de l\'objectif' },
  history: { 'pt-BR': 'Histórico', 'en-US': 'History', 'es-ES': 'Historial', 'fr-FR': 'Historique' },
  recentHistory: { 'pt-BR': 'Histórico Recente', 'en-US': 'Recent History', 'es-ES': 'Historial Reciente', 'fr-FR': 'Historique Récent' },
  noHistoryInPeriod: { 'pt-BR': 'Ajuste o filtro de data', 'en-US': 'Adjust date filter', 'es-ES': 'Ajuste el filtro de fecha', 'fr-FR': 'Ajuster le filtre de date' },
  butHaveHistoryOutside: { 'pt-BR': '', 'en-US': '', 'es-ES': '', 'fr-FR': '' },
  noHistory: { 'pt-BR': 'Nenhum histórico disponível', 'en-US': 'No history available', 'es-ES': 'No hay historial disponible', 'fr-FR': 'Aucun historique disponible' },
  workedDays: { 'pt-BR': 'Dias Trabalhados', 'en-US': 'Worked Days', 'es-ES': 'Días Trabajados', 'fr-FR': 'Jours Travaillés' },
  goalCompleted: { 'pt-BR': 'Meta concluída', 'en-US': 'Goal completed', 'es-ES': 'Meta completada', 'fr-FR': 'Objectif atteint' },
  excessProfit: { 'pt-BR': 'Lucro Excedente', 'en-US': 'Excess Profit', 'es-ES': 'Beneficio Excedente', 'fr-FR': 'Bénéfice Excédentaire' },
  save: { 'pt-BR': 'Salvar', 'en-US': 'Save', 'es-ES': 'Guardar', 'fr-FR': 'Enregistrer' },
  cancel: { 'pt-BR': 'Cancelar', 'en-US': 'Cancel', 'es-ES': 'Cancelar', 'fr-FR': 'Annuler' },
  confirm: { 'pt-BR': 'Confirmar', 'en-US': 'Confirm', 'es-ES': 'Confirmar', 'fr-FR': 'Confirmer' },
  categoryBudget: { 'pt-BR': 'Orçamento por Categoria', 'en-US': 'Category Budget', 'es-ES': 'Presupuesto por Categoría', 'fr-FR': 'Budget par Catégorie' },
  dailyBudget: { 'pt-BR': 'Gasto Diário', 'en-US': 'Daily Budget', 'es-ES': 'Gasto Diario', 'fr-FR': 'Budget Quotidien' },
  dailyStatus: { 'pt-BR': 'Status Diário', 'en-US': 'Daily Status', 'es-ES': 'Estado Diario', 'fr-FR': 'Statut Quotidien' },
  pendingFixedExpenses: { 'pt-BR': 'Gastos Fixos Lançados', 'en-US': 'Processed Fixed Expenses', 'es-ES': 'Gastos Fijos Procesados', 'fr-FR': 'Dépenses Fixes Traitées' },
  toConfirm: { 'pt-BR': 'para confirmar', 'en-US': 'to confirm', 'es-ES': 'por confirmar', 'fr-FR': 'à confirmer' },
  undo: { 'pt-BR': 'Desfazer', 'en-US': 'Undo', 'es-ES': 'Deshacer', 'fr-FR': 'Annuler' },
  voiceCapture: { 'pt-BR': 'Capturar Voz', 'en-US': 'Voice Capture', 'es-ES': 'Capturar Voz', 'fr-FR': 'Capture Vocale' },
  recording: { 'pt-BR': 'Gravando...', 'en-US': 'Recording...', 'es-ES': 'Grabando...', 'fr-FR': 'Enregistrement...' },
  processingVoice: { 'pt-BR': 'Processando voz...', 'en-US': 'Processing voice...', 'es-ES': 'Procesando voz...', 'fr-FR': 'Traitement de la voix...' },
  speechRecognitionNotSupported: { 'pt-BR': 'Reconhecimento de voz não suportado neste navegador.', 'en-US': 'Speech recognition not supported in this browser.', 'es-ES': 'Reconocimiento de voz no soportado en este navegador.', 'fr-FR': 'Reconnaissance vocale non prise en charge dans ce navigateur.' },
  voiceError: { 'pt-BR': 'Erro ao capturar voz. Tente novamente.', 'en-US': 'Error capturing voice. Try again.', 'es-ES': 'Error al capturar la voz. Intente de nuevo.', 'fr-FR': 'Erreur lors de la capture de la voix. Réessayez.' },
  voiceSuccess: { 'pt-BR': 'Dados preenchidos via voz!', 'en-US': 'Data filled via voice!', 'es-ES': '¡Dados llenados por voz!', 'fr-FR': 'Données remplies par la voix !' },
  goal: { 'pt-BR': 'Meta', 'en-US': 'Goal', 'es-ES': 'Meta', 'fr-FR': 'Objectif' },
  left: { 'pt-BR': 'Falta', 'en-US': 'Left', 'es-ES': 'Falta', 'fr-FR': 'Reste' },
  excess: { 'pt-BR': 'Excedente', 'en-US': 'Excess', 'es-ES': 'Exceso', 'fr-FR': 'Excédent' },
  edit: { 'pt-BR': 'Editar', 'en-US': 'Edit', 'es-ES': 'Editar', 'fr-FR': 'Modifier' },
  delete: { 'pt-BR': 'Excluir', 'en-US': 'Delete', 'es-ES': 'Eliminar', 'fr-FR': 'Supprimer' },
  voiceEntryAIPrompt: { 
    'pt-BR': 'Fale naturalmente o que você deseja registrar e a nossa IA fará o resto por você.', 
    'en-US': 'Speak naturally what you want to register and our AI will do the rest for you.', 
    'es-ES': 'Hable naturalmente lo que desea registrar y nuestra IA hará o resto por usted.', 
    'fr-FR': 'Parlez naturellement de ce que vous souhaitez enregistrer et notre IA fera le reste pour vous.' 
  },
  examples: { 'pt-BR': 'Exemplos', 'en-US': 'Examples', 'es-ES': 'Ejemplos', 'fr-FR': 'Exemples' },
  back: { 'pt-BR': 'Voltar', 'en-US': 'Back', 'es-ES': 'Volver', 'fr-FR': 'Retour' },
  darkMode: { 'pt-BR': 'Modo Escuro', 'en-US': 'Dark Mode', 'es-ES': 'Modo Oscuro', 'fr-FR': 'Mode Sombre' },
  language: { 'pt-BR': 'Idioma', 'en-US': 'Language', 'es-ES': 'Idioma', 'fr-FR': 'Langue' },
  profile: { 'pt-BR': 'Perfil', 'en-US': 'Profile', 'es-ES': 'Perfil', 'fr-FR': 'Profil' },
  firstName: { 'pt-BR': 'Nome', 'en-US': 'First Name', 'es-ES': 'Nombre', 'fr-FR': 'Prénom' },
  name: { 'pt-BR': 'Nome', 'en-US': 'Name', 'es-ES': 'Nombre', 'fr-FR': 'Nom' },
  type: { 'pt-BR': 'Tipo', 'en-US': 'Type', 'es-ES': 'Tipo', 'fr-FR': 'Type' },
  lastName: { 'pt-BR': 'Sobrenome', 'en-US': 'Last Name', 'es-ES': 'Apellido', 'fr-FR': 'Nom de famille' },
  email: { 'pt-BR': 'E-mail', 'en-US': 'Email', 'es-ES': 'Correo electrónico', 'fr-FR': 'E-mail' },
  phone: { 'pt-BR': 'Telefone', 'en-US': 'Phone', 'es-ES': 'Teléfono', 'fr-FR': 'Téléphone' },
  birthDate: { 'pt-BR': 'Data de Nascimento', 'en-US': 'Birth Date', 'es-ES': 'Fecha de Nacimiento', 'fr-FR': 'Date de Naissance' },
  city: { 'pt-BR': 'Cidade', 'en-US': 'City', 'es-ES': 'Ciudad', 'fr-FR': 'Ville' },
  state: { 'pt-BR': 'Estado', 'en-US': 'State', 'es-ES': 'Estado', 'fr-FR': 'État' },
  password: { 'pt-BR': 'Senha', 'en-US': 'Password', 'es-ES': 'Contraseña', 'fr-FR': 'Mot de passe' },
  currentPassword: { 'pt-BR': 'Senha Atual', 'en-US': 'Current Password', 'es-ES': 'Contraseña Actual', 'fr-FR': 'Mot de passe actuel' },
  newPassword: { 'pt-BR': 'Nova Senha', 'en-US': 'New Password', 'es-ES': 'Nueva Contraseña', 'fr-FR': 'Nouveau mot de passe' },
  changePassword: { 'pt-BR': 'Alterar senha', 'en-US': 'Change Password', 'es-ES': 'Cambiar Contraseña', 'fr-FR': 'Changer le mot de passe' },
  editProfile: { 'pt-BR': 'Alterar perfil', 'en-US': 'Edit Profile', 'es-ES': 'Editar Perfil', 'fr-FR': 'Modifier le Profil' },
  brand: { 'pt-BR': 'Marca', 'en-US': 'Brand', 'es-ES': 'Marca', 'fr-FR': 'Marque' },
  model: { 'pt-BR': 'Modelo', 'en-US': 'Model', 'es-ES': 'Modelo', 'fr-FR': 'Modèle' },
  vehicleType: { 'pt-BR': 'Tipo de Veículo', 'en-US': 'Vehicle Type', 'es-ES': 'Tipo de Vehículo', 'fr-FR': 'Type de Véhicule' },
  workload: { 'pt-BR': 'Carga de Trabalho', 'en-US': 'Workload', 'es-ES': 'Carga de Trabajo', 'fr-FR': 'Charge de Travail' },
  daysPerWeek: { 'pt-BR': 'dias / sem.', 'en-US': 'days / week', 'es-ES': 'días / sem.', 'fr-FR': 'jours / sem.' },
  dayPerWeek: { 'pt-BR': 'dia / sem.', 'en-US': 'day / week', 'es-ES': 'día / sem.', 'fr-FR': 'jour / sem.' },
  daysPerMonth: { 'pt-BR': 'dias / mês', 'en-US': 'days / month', 'es-ES': 'días / mes', 'fr-FR': 'jours / mois' },
  dayPerMonth: { 'pt-BR': 'dia / mês', 'en-US': 'day / month', 'es-ES': 'día / mes', 'fr-FR': 'jour / mois' },
  goalHistory: { 'pt-BR': 'Histórico de Metas', 'en-US': 'Goal History', 'es-ES': 'Historial de Metas', 'fr-FR': 'Historique des Objectifs' },
  newGoal: { 'pt-BR': 'Nova Meta', 'en-US': 'New Goal', 'es-ES': 'Nueva Meta', 'fr-FR': 'Nouvel Objectif' },
  noGoalsFound: { 'pt-BR': 'Nenhuma meta encontrada', 'en-US': 'No goals found', 'es-ES': 'No se encontraron metas', 'fr-FR': 'Aucun objectif trouvé' },
  period: { 'pt-BR': 'Período', 'en-US': 'Period', 'es-ES': 'Período', 'fr-FR': 'Période' },
  actions: { 'pt-BR': 'Ações', 'en-US': 'Actions', 'es-ES': 'Acciones', 'fr-FR': 'Actions' },
  defineGoal: { 'pt-BR': 'Defina uma meta', 'en-US': 'Define a goal', 'es-ES': 'Define una meta', 'fr-FR': 'Définir um objectif' },
  goalAlreadyExists: { 
    'pt-BR': 'Já existe uma meta estabelecida para este mês e ano.',
    'en-US': 'A goal already exists for this month and year.',
    'es-ES': 'Ya existe una meta establecida para este mes y año.',
    'fr-FR': 'Un objectif existe déjà pour ce mois et cette année.'
  },
  goalSettingsInfo: { 
    'pt-BR': 'Defina o valor líquido que você deseja ter por mês, ou seja, o valor após subtrair todos os gastos (combustível, alimentação, manutenção, etc).',
    'en-US': 'Define the net amount you want to have per month, i.e., the value after subtracting all expenses (fuel, food, maintenance, etc).',
    'es-ES': 'Define el monto neto que deseas tener por mes, es decir, el valor después de restar todos los gastos (combustible, alimentación, mantenimiento, etc).',
    'fr-FR': 'Définissez le montant net que vous souhaitez avoir par mois, c\'est-à-dire la valeur après soustraction de toutes les dépenses (carburant, nourriture, entretien, etc.).'
  },
  licensePlate: { 'pt-BR': 'Placa', 'en-US': 'License Plate', 'es-ES': 'Placa', 'fr-FR': 'Plaque d\'immatriculation' },
  tankCapacity: { 'pt-BR': 'Capacidade do Tanque (L)', 'en-US': 'Tank Capacity (L)', 'es-ES': 'Capacidad del Tanque (L)', 'fr-FR': 'Capacité du Réservoir (L)' },
  tankCapacityInfo: { 'pt-BR': 'Necessário para calcular o km/l de tanque cheio.', 'en-US': 'Required to calculate full tank km/l.', 'es-ES': 'Necesario para calcular el km/l de tanque lleno.', 'fr-FR': 'Nécessaire pour calcular le km/l de plein.' },
  car: { 'pt-BR': 'Carro', 'en-US': 'Car', 'es-ES': 'Coche', 'fr-FR': 'Voiture' },
  motorcycle: { 'pt-BR': 'Moto', 'en-US': 'Motorcycle', 'es-ES': 'Moto', 'fr-FR': 'Moto' },
  truck: { 'pt-BR': 'Caminhão', 'en-US': 'Truck', 'es-ES': 'Camión', 'fr-FR': 'Camion' },
  van: { 'pt-BR': 'Van', 'en-US': 'Van', 'es-ES': 'Furgoneta', 'fr-FR': 'Van' },
  bus: { 'pt-BR': 'Ônibus', 'en-US': 'Bus', 'es-ES': 'Autobús', 'fr-FR': 'Autobus' },
  pickup: { 'pt-BR': 'Caminhonete', 'en-US': 'Pickup', 'es-ES': 'Camioneta', 'fr-FR': 'Pick-up' },
  saveVehicle: { 'pt-BR': 'Salvar Veículo', 'en-US': 'Save Vehicle', 'es-ES': 'Guardar Vehículo', 'fr-FR': 'Enregistrer le Véhicule' },
  initialValue: { 'pt-BR': 'Valor Inicial', 'en-US': 'Initial Value', 'es-ES': 'Valor Inicial', 'fr-FR': 'Valeur Initiale' },
  depreciation: { 'pt-BR': 'Depreciação', 'en-US': 'Depreciation', 'es-ES': 'Depreciación', 'fr-FR': 'Dépréciation' },
  depreciationTable: { 'pt-BR': 'Tabela de Depreciação', 'en-US': 'Depreciation Table', 'es-ES': 'Tabla de Depreciación', 'fr-FR': 'Tableau de Dépréciation' },
  vehicleValue: { 'pt-BR': 'Valor do Veículo', 'en-US': 'Vehicle Value', 'es-ES': 'Valor del Vehículo', 'fr-FR': 'Valeur du Véhicule' },
  percentageExpenseVsTotal: { 'pt-BR': 'vs Gastos', 'en-US': 'vs Total', 'es-ES': 'vs Gastos', 'fr-FR': 'vs Total' },
  percentageExpenseVsEarnings: { 'pt-BR': 'vs Ganhos', 'en-US': 'vs Total', 'es-ES': 'vs Ganancias', 'fr-FR': 'vs Gains' },
  cycleStart: { 'pt-BR': 'Início Ciclo', 'en-US': 'Cycle Start', 'es-ES': 'Inicio Ciclo', 'fr-FR': 'Début Cycle' },
  cycleEnd: { 'pt-BR': 'Fim Ciclo', 'en-US': 'Cycle End', 'es-ES': 'Fin Ciclo', 'fr-FR': 'Fin Cycle' },
  smartModeEnabledDesc: { 'pt-BR': 'Cálculo baseado em seu histórico real', 'en-US': 'Calculation based on your real history', 'es-ES': 'Cálculo basado en su historial real', 'fr-FR': 'Calcul basé sur votre historique réel' },
  smartModeDisabledDesc: { 'pt-BR': 'Aviso: Dados reais ainda insuficientes', 'en-US': 'Warning: Real data still insufficient', 'es-ES': 'Aviso: Dados reales aún insuficientes', 'fr-FR': 'Avis : Données réelles encore insuffisantes' },
  depreciationRate: { 'pt-BR': 'Taxa de Depreciação (%)', 'en-US': 'Depreciation Rate (%)', 'es-ES': 'Tasa de Depreciación (%)', 'fr-FR': 'Taux de Dépréciation (%)' },
  depreciationYears: { 'pt-BR': 'Anos de Uso', 'en-US': 'Years of Use', 'es-ES': 'Años de Uso', 'fr-FR': 'Années d\'Utilisation' },
  depreciationInfo: { 
    'pt-BR': 'O método usado é o exponencial, servindo apenas como uma estimativa. Para resultados mais precisos, consulte a tabela FIPE, pois ela considera diversos outros fatores de mercado.',
    'en-US': 'The method used is exponential, serving only as an estimate. For more accurate results, consult the FIPE table, as it considers many other market factors.',
    'es-ES': 'El método utilizado es exponencial, sirviendo solo como una estimación. Para resultados más precisos, consulte la tabla FIPE, ya que considera muchos otros factores del mercado.',
    'fr-FR': 'La méthode utilisée est exponentielle, ne servant que d\'estimation. Pour des résultats plus précis, consultez le tableau FIPE, car il prend en compte de nombreux autres facteurs du marché.'
  },
  exponential: { 'pt-BR': 'Exponencial', 'en-US': 'Exponential', 'es-ES': 'Exponencial', 'fr-FR': 'Exponentiel' },
  years: { 'pt-BR': 'anos', 'en-US': 'years', 'es-ES': 'años', 'fr-FR': 'ans' },
  driver: { 'pt-BR': 'Condutor', 'en-US': 'Driver', 'es-ES': 'Conductor', 'fr-FR': 'Conducteur' },
  currentOdometer: { 'pt-BR': 'KMs Atualmente', 'en-US': 'Current KMs', 'es-ES': 'KMs Actuales', 'fr-FR': 'KMs Actuels' },
  currentOdometerInfo: { 
    'pt-BR': 'O KM total do veículo hoje. Ele é atualizado automaticamente pelos registros.', 
    'en-US': 'Total vehicle KM today. Updated automatically from records.', 
    'es-ES': 'KM total del vehículo hoy. Se actualiza automáticamente por registros.', 
    'fr-FR': 'Kilométrage total du véhicule aujourd\'hui. Mis à jour automatiquement par les enregistrements.' 
  },
  monthlyGoal: { 'pt-BR': 'Meta Mensal', 'en-US': 'Monthly Goal', 'es-ES': 'Meta Mensual', 'fr-FR': 'Objectif Mensuel' },
  dailyGoal: { 'pt-BR': 'Meta Diária', 'en-US': 'Daily Goal', 'es-ES': 'Meta Diaria', 'fr-FR': 'Objectif Quotidien' },
  weeklyGoal: { 'pt-BR': 'Meta Semanal', 'en-US': 'Weekly Goal', 'es-ES': 'Meta Semanal', 'fr-FR': 'Objectif Hebdomadaire' },
  yearlyGoal: { 'pt-BR': 'Meta Anual', 'en-US': 'Yearly Goal', 'es-ES': 'Meta Anual', 'fr-FR': 'Objectif Annuel' },
  ipva: { 'pt-BR': 'IPVA', 'en-US': 'IPVA', 'es-ES': 'IPVA', 'fr-FR': 'IPVA' },
  insurance: { 'pt-BR': 'Seguro', 'en-US': 'Insurance', 'es-ES': 'Seguro', 'fr-FR': 'Assurance' },
  financing: { 'pt-BR': 'Financiamento', 'en-US': 'Financing', 'es-ES': 'Financiamiento', 'fr-FR': 'Financement' },
  carInstallment: { 'pt-BR': 'Parcela do Carro', 'en-US': 'Car Installment', 'es-ES': 'Parcela del Coche', 'fr-FR': 'Versement Voiture' },
  licensing: { 'pt-BR': 'Licenciamento', 'en-US': 'Licensing', 'es-ES': 'Licenciamiento', 'fr-FR': 'Licence' },
  registration: { 'pt-BR': 'Emplacamento', 'en-US': 'Registration', 'es-ES': 'Emplacamiento', 'fr-FR': 'Immatriculation' },
  variableIncomeCategories: { 'pt-BR': 'Ganhos', 'en-US': 'Earnings', 'es-ES': 'Ganancias', 'fr-FR': 'Gains' },
  fixedIncomeCategories: { 'pt-BR': 'Ganhos Fixos', 'en-US': 'Fixed Earnings', 'es-ES': 'Ganancias Fijas', 'fr-FR': 'Gains Fixes' },
  variableExpenseCategories: { 'pt-BR': 'Gastos', 'en-US': 'Expenses', 'es-ES': 'Gastos', 'fr-FR': 'Dépenses' },
  fixedExpenseCategories: { 'pt-BR': 'Gastos Fixos', 'en-US': 'Fixed Expenses', 'es-ES': 'Gastos Fijos', 'fr-FR': 'Dépenses Fixes' },
  fixedExpenses: { 'pt-BR': 'Gastos Fixos', 'en-US': 'Fixed Expenses', 'es-ES': 'Gastos Fijos', 'fr-FR': 'Dépenses Fixes' },
  pendingNotifications: { 'pt-BR': 'notificações pendentes', 'en-US': 'pending notifications', 'es-ES': 'notificaciones pendientes', 'fr-FR': 'notifications en attente' },
  noPendingFixedExpenses: { 'pt-BR': 'Nenhuma notificação de gasto fixo', 'en-US': 'No pending fixed expense notifications', 'es-ES': 'No hay notificaciones de gastos fijos', 'fr-FR': 'Aucune notification de dépense fixe' },
  uberx: { 'pt-BR': 'UberX', 'en-US': 'UberX', 'es-ES': 'UberX', 'fr-FR': 'UberX' },
  ubercomfort: { 'pt-BR': 'Uber Comfort', 'en-US': 'Uber Comfort', 'es-ES': 'Uber Comfort', 'fr-FR': 'Uber Comfort' },
  uberblack: { 'pt-BR': 'Uber Black', 'en-US': 'Uber Black', 'es-ES': 'Uber Black', 'fr-FR': 'Uber Black' },
  uberbag: { 'pt-BR': 'Uber Bag', 'en-US': 'Uber Bag', 'es-ES': 'Uber Bag', 'fr-FR': 'Uber Bag' },
  '99pop': { 'pt-BR': '99 Pop', 'en-US': '99 Pop', 'es-ES': '99 Pop', 'fr-FR': '99 Pop' },
  '99taxi': { 'pt-BR': '99 Taxi', 'en-US': '99 Taxi', 'es-ES': '99 Taxi', 'fr-FR': '99 Taxi' },
  '99top': { 'pt-BR': '99 Top', 'en-US': '99 Top', 'es-ES': '99 Top', 'fr-FR': '99 Top' },
  indrive: { 'pt-BR': 'inDrive', 'en-US': 'inDrive', 'es-ES': 'inDrive', 'fr-FR': 'inDrive' },
  maxim: { 'pt-BR': 'Maxim', 'en-US': 'Maxim', 'es-ES': 'Maxim', 'fr-FR': 'Maxim' },
  cabify: { 'pt-BR': 'Cabify', 'en-US': 'Cabify', 'es-ES': 'Cabify', 'fr-FR': 'Cabify' },
  ladydriver: { 'pt-BR': 'Lady Driver', 'en-US': 'Lady Driver', 'es-ES': 'Lady Driver', 'fr-FR': 'Lady Driver' },
  sity: { 'pt-BR': 'Sity', 'en-US': 'Sity', 'es-ES': 'Sity', 'fr-FR': 'Sity' },
  ifood: { 'pt-BR': 'iFood', 'en-US': 'iFood', 'es-ES': 'iFood', 'fr-FR': 'iFood' },
  rappi: { 'pt-BR': 'Rappi', 'en-US': 'Rappi', 'es-ES': 'Rappi', 'fr-FR': 'Rappi' },
  james: { 'pt-BR': 'James', 'en-US': 'James', 'es-ES': 'James', 'fr-FR': 'James' },
  wappa: { 'pt-BR': 'Wappa', 'en-US': 'Wappa', 'es-ES': 'Wappa', 'fr-FR': 'Wappa' },
  taxi: { 'pt-BR': 'Táxi', 'en-US': 'Taxi', 'es-ES': 'Taxi', 'fr-FR': 'Taxi' },
  freight: { 'pt-BR': 'Frete', 'en-US': 'Freight', 'es-ES': 'Flete', 'fr-FR': 'Fret' },
  carpool: { 'pt-BR': 'Carona', 'en-US': 'Carpool', 'es-ES': 'Carpool', 'fr-FR': 'Carpool' },
  fixed: { 'pt-BR': 'Fixo', 'en-US': 'Fixed', 'es-ES': 'Fijo', 'fr-FR': 'Fixe' },
  variable: { 'pt-BR': 'Variável', 'en-US': 'Variable', 'es-ES': 'Variable', 'fr-FR': 'Variable' },
  moreThanPrevPeriod: { 'pt-BR': 'vs. {period}', 'en-US': 'vs. {period}', 'es-ES': 'vs. {period}', 'fr-FR': 'vs. {period}' },
  yesterday: { 'pt-BR': 'ontem', 'en-US': 'yesterday', 'es-ES': 'ayer', 'fr-FR': 'hier' },
  prevWeek: { 'pt-BR': 'semana anterior', 'en-US': 'previous week', 'es-ES': 'semana anterior', 'fr-FR': 'semaine précédente' },
  prevMonth: { 'pt-BR': 'mês anterior', 'en-US': 'previous month', 'es-ES': 'mes anterior', 'fr-FR': 'mois précédent' },
  prevYear: { 'pt-BR': 'ano anterior', 'en-US': 'previous year', 'es-ES': 'año anterior', 'fr-FR': 'année précédente' },
  increaseOf: { 'pt-BR': 'aumento de', 'en-US': 'increase of', 'es-ES': 'aumento de', 'fr-FR': 'augmentation de' },
  decreaseOf: { 'pt-BR': 'redução de', 'en-US': 'decrease of', 'es-ES': 'reducción de', 'fr-FR': 'diminution de' },
  appPreferences: { 'pt-BR': 'Preferências do App', 'en-US': 'App Preferences', 'es-ES': 'Preferencias de la App', 'fr-FR': 'Préférences de l\'App' },
  helpSupport: { 'pt-BR': 'Ajuda e Suporte', 'en-US': 'Help & Support', 'es-ES': 'Ayuda y Soporte', 'fr-FR': 'Aide et Support' },
  faq: { 'pt-BR': 'FAQ / Central', 'en-US': 'FAQ / Center', 'es-ES': 'FAQ / Centro', 'fr-FR': 'FAQ / Centre' },
  liveChat: { 'pt-BR': 'Chat Ao Vivo', 'en-US': 'Live Chat', 'es-ES': 'Chat en Vivo', 'fr-FR': 'Chat en Direct' },
  expenseCategories: { 'pt-BR': 'Categorias de Gastos', 'en-US': 'Expense Categories', 'es-ES': 'Categorías de Gastos', 'fr-FR': 'Catégories de Dépenses' },
  incomeCategories: { 'pt-BR': 'Categorias de Ganhos', 'en-US': 'Income Categories', 'es-ES': 'Categorías de Ingresos', 'fr-FR': 'Catégories de Revenus' },
  newCategory: { 'pt-BR': 'Novo Gasto', 'en-US': 'New Expense', 'es-ES': 'Nuevo Gasto', 'fr-FR': 'Nouvelle Dépense' },
  newPlatform: { 'pt-BR': 'Novo Ganho', 'en-US': 'New Income', 'es-ES': 'Nuevo Ingreso', 'fr-FR': 'Nouveau Revenu' },
  newSubcategory: { 'pt-BR': 'Nova Subcategoria', 'en-US': 'New Subcategory', 'es-ES': 'Nueva Subcategoría', 'fr-FR': 'Nouvelle Sous-catégorie' },
  addSubcategory: { 'pt-BR': 'Adicionar Subcategoria', 'en-US': 'Add Subcategory', 'es-ES': 'Añadir Subcategoría', 'fr-FR': 'Ajouter une Sous-catégorie' },
  workHours: { 'pt-BR': 'Horas de Trabalho', 'en-US': 'Work Hours', 'es-ES': 'Horas de Trabajo', 'fr-FR': 'Heures de Travail' },
  workDaysPerWeek: { 'pt-BR': 'Dias por Semana', 'en-US': 'Days per Week', 'es-ES': 'Días por Semana', 'fr-FR': 'Jours par Semaine' },
  workDaysPerMonth: { 'pt-BR': 'Dias por Mês', 'en-US': 'Dias por Mês', 'es-ES': 'Días por Mes', 'fr-FR': 'Jours par Mois' },
  restoreDefaults: { 'pt-BR': 'Restaurar Padrão', 'en-US': 'Restore Defaults', 'es-ES': 'Restaurar Predeterminados', 'fr-FR': 'Restaurer les Paramètres' },
  confirmRestoreCategories: { 'pt-BR': 'Isso irá restaurar as categorias para o padrão original. Suas categorias personalizadas serão mantidas, mas as padrões serão resetadas. Deseja continuar?', 'en-US': 'This will restore categories to the original default. Your custom categories will be kept, but defaults will be reset. Do you want to continue?', 'es-ES': 'Esto restaurará las categorías al valor predeterminado original. Se mantendrán sus categorías personalizadas, pero se restablecerán las predeterminadas. ¿Desea continuar?', 'fr-FR': 'Cela restaurera les catégories par défaut. Vos catégories personnalisées seront conservées, mas les valeurs par défaut seront réinitialisées. Voulez-vous continuer?' },
  confirmRestorePlatforms: { 'pt-BR': 'Isso irá restaurar os ganhos (plataformas) para o padrão original. Suas plataformas personalizadas serão mantidas, mas as padrões serão resetadas. Deseja continuar?', 'en-US': 'This will restore income platforms to the original default. Your custom platforms will be kept, but defaults will be reset. Do you want to continue?', 'es-ES': 'Esto restaurará las plataformas de ingresos al valor predeterminado original. Se mantendrán sus plataformas personalizadas, pero se restablecerán las predeterminadas. ¿Desea continuar?', 'fr-FR': 'Cela restaurera les plateformes de revenus par défaut. Vos plateformes personnalisées seront conservées, mais les valeurs par défaut seront réinitialisées. Voulez-vous continuer?' },
  fieldsRequired: { 'pt-BR': 'Campos obrigatórios!', 'en-US': 'Fields required!', 'es-ES': '¡Campos obligatorios!', 'fr-FR': 'Champs requis !' },
  performance: { 'pt-BR': 'Performance', 'en-US': 'Performance', 'es-ES': 'Desempeño', 'fr-FR': 'Performance' },
  invalidPassword: { 'pt-BR': 'Senha atual incorreta!', 'en-US': 'Incorrect current password!', 'es-ES': '¡Contraseña actual incorrecta!', 'fr-FR': 'Mot de passe actuel incorrect !' },
  termsPrivacy: { 'pt-BR': 'Termos e Privacidade', 'en-US': 'Terms & Privacy', 'es-ES': 'Términos y Privacidad', 'fr-FR': 'Conditions et Confidentialité' },
  income: { 'pt-BR': 'Ganho', 'en-US': 'Income', 'es-ES': 'Ingreso', 'fr-FR': 'Revenu' },
  expense: { 'pt-BR': 'Gasto', 'en-US': 'Expense', 'es-ES': 'Gasto', 'fr-FR': 'Dépense' },
  fuel: { 'pt-BR': 'Combustível', 'en-US': 'Fuel', 'es-ES': 'Combustible', 'fr-FR': 'Carburant' },
  maintenance: { 'pt-BR': 'Manutenção', 'en-US': 'Maintenance', 'es-ES': 'Mantenimiento', 'fr-FR': 'Entretien' },
  food: { 'pt-BR': 'Alimentação', 'en-US': 'Food', 'es-ES': 'Alimentación', 'fr-FR': 'Alimentation' },
  rent: { 'pt-BR': 'Aluguel', 'en-US': 'Rent', 'es-ES': 'Alquiler', 'fr-FR': 'Loyer' },
  parking: { 'pt-BR': 'Estacionamento', 'en-US': 'Parking', 'es-ES': 'Estacionamiento', 'fr-FR': 'Parking' },
  tow: { 'pt-BR': 'Guincho', 'en-US': 'Tow', 'es-ES': 'Grúa', 'fr-FR': 'Remorquage' },
  fine: { 'pt-BR': 'Multa', 'en-US': 'Fine', 'es-ES': 'Multa', 'fr-FR': 'Amende' },
  toll: { 'pt-BR': 'Pedágio', 'en-US': 'Toll', 'es-ES': 'Peaje', 'fr-FR': 'Péage' },
  washing: { 'pt-BR': 'Lavagem', 'en-US': 'Washing', 'es-ES': 'Lavado', 'fr-FR': 'Lavage' },
  internet: { 'pt-BR': 'Internet', 'en-US': 'Internet', 'es-ES': 'Internet', 'fr-FR': 'Internet' },
  ferry: { 'pt-BR': 'Balsa', 'en-US': 'Ferry', 'es-ES': 'Ferry', 'fr-FR': 'Ferry' },
  tax: { 'pt-BR': 'MEI / Imposto', 'en-US': 'MEI / Tax', 'es-ES': 'MEI / Impuesto', 'fr-FR': 'MEI / Impôt' },
  tracker: { 'pt-BR': 'Rastreador Veicular', 'en-US': 'Vehicle Tracker', 'es-ES': 'Rastreador Vehicular', 'fr-FR': 'Traceur Véhicule' },
  consortium: { 'pt-BR': 'Consórcio Veicular', 'en-US': 'Vehicle Consortium', 'es-ES': 'Consorcio Vehicular', 'fr-FR': 'Consortium Véhicule' },
  accessories: { 'pt-BR': 'Acessórios', 'en-US': 'Accessories', 'es-ES': 'Accesorios', 'fr-FR': 'Accessoires' },
  
  // Subcategories
  multimedia: { 'pt-BR': 'Multimídia', 'en-US': 'Multimedia', 'es-ES': 'Multimedia', 'fr-FR': 'Multimédia' },
  alarm: { 'pt-BR': 'Alarme', 'en-US': 'Alarm', 'es-ES': 'Alarma', 'fr-FR': 'Alarme' },
  other: { 'pt-BR': 'Outro', 'en-US': 'Other', 'es-ES': 'Otro', 'fr-FR': 'Autre' },
  gasolineCommon: { 'pt-BR': 'Gasolina Comum', 'en-US': 'Regular Gasoline', 'es-ES': 'Gasolina Común', 'fr-FR': 'Essence Ordinaire' },
  gasolineAdditive: { 'pt-BR': 'Gasolina Aditivada', 'en-US': 'Additivated Gasoline', 'es-ES': 'Gasolina Aditivada', 'fr-FR': 'Essence Additivée' },
  gasolinePremium: { 'pt-BR': 'Gasolina Premium', 'en-US': 'Premium Gasoline', 'es-ES': 'Gasolina Premium', 'fr-FR': 'Essence Premium' },
  ethanol: { 'pt-BR': 'Etanol', 'en-US': 'Ethanol', 'es-ES': 'Etanol', 'fr-FR': 'Éthanol' },
  gnv: { 'pt-BR': 'GNV', 'en-US': 'CNG', 'es-ES': 'GNC', 'fr-FR': 'GNV' },
  diesel: { 'pt-BR': 'Diesel', 'en-US': 'Diesel', 'es-ES': 'Diesel', 'fr-FR': 'Diesel' },
  alignment: { 'pt-BR': 'Alinhamento', 'en-US': 'Alignment', 'es-ES': 'Alineación', 'fr-FR': 'Alignement' },
  balancing: { 'pt-BR': 'Balanceamento', 'en-US': 'Balancing', 'es-ES': 'Balanceo', 'fr-FR': 'Équilibrage' },
  calibration: { 'pt-BR': 'Calibragem', 'en-US': 'Calibration', 'es-ES': 'Calibración', 'fr-FR': 'Calibrage' },
  airFilter: { 'pt-BR': 'Filtro de Ar', 'en-US': 'Air Filter', 'es-ES': 'Filtro de Aire', 'fr-FR': 'Filtre à Air' },
  fuelFilter: { 'pt-BR': 'Filtro de Combustível', 'en-US': 'Fuel Filter', 'es-ES': 'Filtro de Combustible', 'fr-FR': 'Filtre à Carburant' },
  oilFilter: { 'pt-BR': 'Filtro de Óleo', 'en-US': 'Oil Filter', 'es-ES': 'Filtro de Aceite', 'fr-FR': 'Filtre à Huile' },
  brakeFluid: { 'pt-BR': 'Fluido de Freio', 'en-US': 'Brake Fluid', 'es-ES': 'Líquido de Frenos', 'fr-FR': 'Liquide de Frein' },
  transmissionFluid: { 'pt-BR': 'Fluido de Transmissão', 'en-US': 'Transmission Fluid', 'es-ES': 'Líquido de Transmisión', 'fr-FR': 'Huile de Transmission' },
  oilChange: { 'pt-BR': 'Troca de Óleo', 'en-US': 'Oil Change', 'es-ES': 'Cambio de Aceite', 'fr-FR': 'Vidange' },
  sparkPlugs: { 'pt-BR': 'Velas de Ignição', 'en-US': 'Spark Plugs', 'es-ES': 'Bujías', 'fr-FR': 'Bougies' },
  battery: { 'pt-BR': 'Bateria', 'en-US': 'Battery', 'es-ES': 'Batería', 'fr-FR': 'Batterie' },
  fuelPump: { 'pt-BR': 'Bomba de Combustível', 'en-US': 'Fuel Pump', 'es-ES': 'Bomba de Combustible', 'fr-FR': 'Pompe à Essence' },
  horn: { 'pt-BR': 'Buzina', 'en-US': 'Horn', 'es-ES': 'Bocina', 'fr-FR': 'Klaxon' },
  bodywork: { 'pt-BR': 'Funilaria', 'en-US': 'Bodywork', 'es-ES': 'Carrocería', 'fr-FR': 'Carrosserie' },
  powerSteering: { 'pt-BR': 'Direção Hidráulica', 'en-US': 'Power Steering', 'es-ES': 'Dirección Hidráulica', 'fr-FR': 'Direction Assistée' },
  mirrors: { 'pt-BR': 'Retrovisores', 'en-US': 'Mirrors', 'es-ES': 'Retrovisores', 'fr-FR': 'Rétroviseurs' },
  brakePad: { 'pt-BR': 'Pastilha de Freio', 'en-US': 'Brake Pad', 'es-ES': 'Pastilla de Freno', 'fr-FR': 'Plaquette de Frein' },
  radiator: { 'pt-BR': 'Radiador', 'en-US': 'Radiator', 'es-ES': 'Radiador', 'fr-FR': 'Radiateur' },
  suspension: { 'pt-BR': 'Suspensão', 'en-US': 'Suspension', 'es-ES': 'Suspensión', 'fr-FR': 'Suspension' },
  brakeChange: { 'pt-BR': 'Troca de Freios', 'en-US': 'Brake Change', 'es-ES': 'Cambio de Frenos', 'fr-FR': 'Changement de Freins' },
  timingBelt: { 'pt-BR': 'Correia Dentada', 'en-US': 'Timing Belt', 'es-ES': 'Correa de Distribución', 'fr-FR': 'Courroie de Distribution' },
  alternator: { 'pt-BR': 'Alternador', 'en-US': 'Alternator', 'es-ES': 'Alternador', 'fr-FR': 'Alternateur' },
  starterMotor: { 'pt-BR': 'Motor de Partida', 'en-US': 'Starter Motor', 'es-ES': 'Motor de Arranque', 'fr-FR': 'Démarreur' },
  electronicInjection: { 'pt-BR': 'Injeção Eletrônica', 'en-US': 'Electronic Injection', 'es-ES': 'Inyección Electrónica', 'fr-FR': 'Injection Électronique' },
  oxygenSensor: { 'pt-BR': 'Sonda Lambda', 'en-US': 'Oxygen Sensor', 'es-ES': 'Sonda Lambda', 'fr-FR': 'Sonde Lambda' },
  catalyticConverter: { 'pt-BR': 'Catalisador', 'en-US': 'Catalytic Converter', 'es-ES': 'Catalizador', 'fr-FR': 'Catalyseur' },
  airConditioning: { 'pt-BR': 'Ar Condicionado', 'en-US': 'Air Conditioning', 'es-ES': 'Aire Acondicionado', 'fr-FR': 'Climatisation' },
  electricalSystem: { 'pt-BR': 'Sistema Elétrico', 'en-US': 'Electrical System', 'es-ES': 'Sistema Eléctrico', 'fr-FR': 'Système Électrique' },
  lighting: { 'pt-BR': 'Iluminação', 'en-US': 'Lighting', 'es-ES': 'Iluminación', 'fr-FR': 'Éclairage' },
  lunch: { 'pt-BR': 'Almoço', 'en-US': 'Lunch', 'es-ES': 'Almuerzo', 'fr-FR': 'Déjeuner' },
  snack: { 'pt-BR': 'Lanche', 'en-US': 'Snack', 'es-ES': 'Merienda', 'fr-FR': 'Goûter' },
  dinner: { 'pt-BR': 'Jantar', 'en-US': 'Dinner', 'es-ES': 'Cena', 'fr-FR': 'Dîner' },
  otherCategory: { 'pt-BR': 'Outra Categoria', 'en-US': 'Other Category', 'es-ES': 'Otra Categoría', 'fr-FR': 'Autre Catégorie' },
  extraSensors: { 'pt-BR': 'Sensores Extras', 'en-US': 'Extra Sensors', 'es-ES': 'Sensores Extras', 'fr-FR': 'Capteurs Extras' },
  phoneHolder: { 'pt-BR': 'Suporte de Celular', 'en-US': 'Phone Holder', 'es-ES': 'Soporte Celular', 'fr-FR': 'Support Téléphone' },
  painting: { 'pt-BR': 'Pintura', 'en-US': 'Painting', 'es-ES': 'Pintura', 'fr-FR': 'Peinture' },
  film: { 'pt-BR': 'Película', 'en-US': 'Film', 'es-ES': 'Película', 'fr-FR': 'Film' },
  wrapping: { 'pt-BR': 'Envelopamento', 'en-US': 'Wrapping', 'es-ES': 'Envoltura', 'fr-FR': 'Enveloppement' },
  camera: { 'pt-BR': 'Câmera', 'en-US': 'Camera', 'es-ES': 'Cámara', 'fr-FR': 'Caméra' },
  led: { 'pt-BR': 'LED', 'en-US': 'LED', 'es-ES': 'LED', 'fr-FR': 'LED' },
  floorMat: { 'pt-BR': 'Tapete', 'en-US': 'Floor Mat', 'es-ES': 'Tapete', 'fr-FR': 'Tapis' },
  roofRack: { 'pt-BR': 'Bagageiro de Teto', 'en-US': 'Roof Rack', 'es-ES': 'Portaequipajes', 'fr-FR': 'Galerie de Toit' },
  fairing: { 'pt-BR': 'Carenagem', 'en-US': 'Fairing', 'es-ES': 'Carenado', 'fr-FR': 'Carénage' },
  brakePedal: { 'pt-BR': 'Pedal de Freio', 'en-US': 'Brake Pedal', 'es-ES': 'Pedal de Freno', 'fr-FR': 'Pédale de Frein' },
  gearPedal: { 'pt-BR': 'Pedal de Marcha', 'en-US': 'Gear Pedal', 'es-ES': 'Pedal de Marcha', 'fr-FR': 'Pédale de Vitesse' },
  rectification: { 'pt-BR': 'Retífica', 'en-US': 'Rectification', 'es-ES': 'Rectificación', 'fr-FR': 'Rectification' },
  cylinderHead: { 'pt-BR': 'Cabeçote', 'en-US': 'Cylinder Head', 'es-ES': 'Culata', 'fr-FR': 'Culasse' },
  disc: { 'pt-BR': 'Disco', 'en-US': 'Disc', 'es-ES': 'Disco', 'fr-FR': 'Disque' },
  crankcase: { 'pt-BR': 'Cárter', 'en-US': 'Crankcase', 'es-ES': 'Cárter', 'fr-FR': 'Carter' },
  hydraulicJack: { 'pt-BR': 'Macaco Hidráulico', 'en-US': 'Hydraulic Jack', 'es-ES': 'Gato Hidráulico', 'fr-FR': 'Cric Hydraulique' },
  wrench: { 'pt-BR': 'Chave', 'en-US': 'Wrench', 'es-ES': 'Llave', 'fr-FR': 'Clé' },
  fireExtinguisher: { 'pt-BR': 'Extintor de Incêndio', 'en-US': 'Fire Extinguisher', 'es-ES': 'Extintor de Incendios', 'fr-FR': 'Extincteur' },
  triangle: { 'pt-BR': 'Triângulo', 'en-US': 'Triangle', 'es-ES': 'Triángulo', 'fr-FR': 'Triangle' },
  firstAidKit: { 'pt-BR': 'Kit Primeiros Socorros', 'en-US': 'First Aid Kit', 'es-ES': 'Kit de Primeros Auxilios', 'fr-FR': 'Kit de Premiers Secours' },
  exhaust: { 'pt-BR': 'Escapamento', 'en-US': 'Exhaust', 'es-ES': 'Escape', 'fr-FR': 'Échappement' },
  transmissionKit: { 'pt-BR': 'Kit Transmissão', 'en-US': 'Transmission Kit', 'es-ES': 'Kit Transmisión', 'fr-FR': 'Kit Transmission' },
  bearings: { 'pt-BR': 'Rolamentos', 'en-US': 'Bearings', 'es-ES': 'Rodamientos', 'fr-FR': 'Roulements' },
  lubrication: { 'pt-BR': 'Lubrificação', 'en-US': 'Lubrication', 'es-ES': 'Lubricación', 'fr-FR': 'Lubrification' },
  clutch: { 'pt-BR': 'Embreagem', 'en-US': 'Clutch', 'es-ES': 'Embrague', 'fr-FR': 'Embrayage' },
  selectCategory: { 'pt-BR': 'Selecione a Categoria', 'en-US': 'Select Category', 'es-ES': 'Seleccionar Categoría', 'fr-FR': 'Sélectionner une Catégorie' },
  amount: { 'pt-BR': 'Valor', 'en-US': 'Amount', 'es-ES': 'Valor', 'fr-FR': 'Montant' },
  notes: { 'pt-BR': 'Observação', 'en-US': 'Observation', 'es-ES': 'Observaciones', 'fr-FR': 'Notes' },
  date: { 'pt-BR': 'Data', 'en-US': 'Date', 'es-ES': 'Fecha', 'fr-FR': 'Date' },
  liters: { 'pt-BR': 'Litros', 'en-US': 'Liters', 'es-ES': 'Litros', 'fr-FR': 'Litres' },
  pricePerLiter: { 'pt-BR': 'Preço por Litro', 'en-US': 'Price per Liter', 'es-ES': 'Precio por Litro', 'fr-FR': 'Prix par Litre' },
  gnvVolume: { 'pt-BR': 'Metros Cúbicos (m³)', 'en-US': 'Cubic Meters (m³)', 'es-ES': 'Metros Cúbicos (m³)', 'fr-FR': 'Mètres Cubes (m³)' },
  gnvPrice: { 'pt-BR': 'Preço por m³', 'en-US': 'Price per m³', 'es-ES': 'Precio por m³', 'fr-FR': 'Prix par m³' },
  subCategory: { 'pt-BR': 'Subcategoria', 'en-US': 'Subcategory', 'es-ES': 'Subcategoría', 'fr-FR': 'Sous-catégorie' },
  success: { 'pt-BR': 'Sucesso!', 'en-US': 'Success!', 'es-ES': '¡Éxito!', 'fr-FR': 'Succès !' },
  makeDefault: { 'pt-BR': 'Tornar Padrão', 'en-US': 'Make Default', 'es-ES': 'Hacer Predeterminado', 'fr-FR': 'Rendre par Défaut' },
  confirmMakeDefault: { 'pt-BR': 'Tem certeza que deseja tornar esta categoria um padrão do sistema? Você não poderá mais editá-la ou excluí-la.', 'en-US': 'Are you sure you want to make this category a system default? You will no longer be able to edit or delete it.', 'es-ES': '¿Estás seguro de que deseas que esta categoría sea predeterminada del sistema? Ya no podrás editarla ni eliminarla.', 'fr-FR': 'Êtes-vous sûr de vouloir faire de cette catégorie un standard du système ? Vous ne pourrez plus la modifier ou la supprimer.' },
  error: { 'pt-BR': 'Erro!', 'en-US': 'Error!', 'es-ES': '¡Error!', 'fr-FR': 'Erreur !' },
  confirmIncome: { 'pt-BR': 'Confirmar Ganho', 'en-US': 'Confirm Income', 'es-ES': 'Confirmar Ingreso', 'fr-FR': 'Confirmer le Revenu' },
  tapToSpeak: { 'pt-BR': 'Lançamento por voz', 'en-US': 'Voice Entry', 'es-ES': 'Lanzamiento por voz', 'fr-FR': 'Entrée vocale' },
  voiceEntry: { 'pt-BR': 'Lançamento por voz', 'en-US': 'Voice Entry', 'es-ES': 'Lanzamiento por voz', 'fr-FR': 'Entrée vocale' },
  tapToRecordText: { 'pt-BR': 'Lançamento por voz', 'en-US': 'Voice Entry', 'es-ES': 'Lanzamiento por voz', 'fr-FR': 'Entrée vocale' },
  confirmExpense: { 'pt-BR': 'Confirmar Gasto', 'en-US': 'Confirm Expense', 'es-ES': 'Confirmar Gasto', 'fr-FR': 'Confirmer la Dépense' },
  editIncome: { 'pt-BR': 'Editar Ganho', 'en-US': 'Edit Income', 'es-ES': 'Editar Ingreso', 'fr-FR': 'Modifier le Revenu' },
  editExpense: { 'pt-BR': 'Editar Gasto', 'en-US': 'Edit Expense', 'es-ES': 'Editar Gasto', 'fr-FR': 'Modifier la Dépense' },
  whatToRegister: { 'pt-BR': 'O que deseja registrar?', 'en-US': 'What do you want to register?', 'es-ES': '¿Qué desea registrar?', 'fr-FR': 'Que voulez-vous enregistrer ?' },
  selectTypeToContinue: { 'pt-BR': 'Selecione o tipo de lançamento para continuar.', 'en-US': 'Select the type of entry to continue.', 'es-ES': 'Seleccione el tipo de entrada para continuar.', 'fr-FR': 'Sélectionnez le type d\'entrée pour continuer.' },
  registerIncome: { 'pt-BR': 'Registrar Ganho', 'en-US': 'Register Income', 'es-ES': 'Registrar Ingreso', 'fr-FR': 'Enregistrer un Revenu' },
  fullTank: { 'pt-BR': 'Tanque Completo', 'en-US': 'Full Tank', 'es-ES': 'Tanque Completo', 'fr-FR': 'Plein' },
  partialTank: { 'pt-BR': 'Tanque Parcial', 'en-US': 'Partial Tank', 'es-ES': 'Tanque Parcial', 'fr-FR': 'Partiel' },
  odometer: { 'pt-BR': 'Odômetro', 'en-US': 'Odometer', 'es-ES': 'Odómetro', 'fr-FR': 'Odomètre' },
  consumption: { 'pt-BR': 'Consumo', 'en-US': 'Consumption', 'es-ES': 'Consumo', 'fr-FR': 'Consommation' },
  kmPerLiter: { 'pt-BR': 'km/L', 'en-US': 'km/L', 'es-ES': 'km/L', 'fr-FR': 'km/L' },
  kmPerCubicMeter: { 'pt-BR': 'km/m³', 'en-US': 'km/m³', 'es-ES': 'km/m³', 'fr-FR': 'km/m³' },
  costPerKm: { 'pt-BR': 'Custo por KM', 'en-US': 'Cost per KM', 'es-ES': 'Costo por KM', 'fr-FR': 'Coût par KM' },
  odometerMustBeIncreasing: { 'pt-BR': 'O odômetro deve ser maior que o registro anterior', 'en-US': 'Odometer must be greater than the previous record', 'es-ES': 'El odómetro debe ser mayor que el registro anterior', 'fr-FR': 'L\'odomètre doit être supérieur à l\'enregistrement précédent' },
  odometerInfo: { 'pt-BR': 'KMs no momento do abastecimento', 'en-US': 'KMs at the time of fueling', 'es-ES': 'KMs al momento del abastecimiento', 'fr-FR': 'KMs au moment du ravitaillement' },
  defaultAmount: { 'pt-BR': 'Valor Padrão', 'en-US': 'Default Amount', 'es-ES': 'Valor Predeterminado', 'fr-FR': 'Montant par Défaut' },
  registerExpense: { 'pt-BR': 'Registrar Gasto', 'en-US': 'Register Expense', 'es-ES': 'Registrar Gasto', 'fr-FR': 'Enregistrer une Dépense' },
  incomeDescription: { 'pt-BR': 'Entradas de plataformas, fretes, gorjetas e outros ganhos.', 'en-US': 'Platform entries, freight, tips and other earnings.', 'es-ES': 'Entradas de plataformas, fletes, propinas y otros ingresos.', 'fr-FR': 'Entrées de plateformes, fret, pourboires et autres gains.' },
  expenseDescription: { 'pt-BR': 'Combustível, manutenção, alimentação e custos operacionais.', 'en-US': 'Fuel, maintenance, food and operational costs.', 'es-ES': 'Combustible, mantenimiento, alimentación y costos operativos.', 'fr-FR': 'Carburant, entretien, alimentation et coûts opérationnels.' },
  registerNewIncome: { 'pt-BR': 'Registrar Novo Ganho', 'en-US': 'Register New Income', 'es-ES': 'Registrar Nuevo Ingreso', 'fr-FR': 'Enregistrer un Nouveau Revenu' },
  incomeRegisteredSuccess: { 'pt-BR': 'Ganho registrado com sucesso!', 'en-US': 'Income registered successfully!', 'es-ES': '¡Ingreso registrado con éxito!', 'fr-FR': 'Revenu enregistré avec succès !' },
  incomeDate: { 'pt-BR': 'Data do Ganho', 'en-US': 'Income Date', 'es-ES': 'Fecha del Ingreso', 'fr-FR': 'Date du Revenu' },
  expenseDate: { 'pt-BR': 'Data do Gasto', 'en-US': 'Expense Date', 'es-ES': 'Fecha del Gasto', 'fr-FR': 'Date de la Dépense' },
  hoursWorked: { 'pt-BR': 'Horas Trabalhadas', 'en-US': 'Hours Worked', 'es-ES': 'Horas Trabajadas', 'fr-FR': 'Heures Travaillées' },
  kmDriven: { 'pt-BR': 'KM Rodados', 'en-US': 'KM Driven', 'es-ES': 'KM Recorridos', 'fr-FR': 'KM Parcourus' },
  selectPlatform: { 'pt-BR': '1. Selecione a Plataforma', 'en-US': '1. Select Platform', 'es-ES': '1. Seleccione la Plataforma', 'fr-FR': '1. Sélectionnez la Plateforme' },
  entryData: { 'pt-BR': '2. Dados do Lançamento', 'en-US': '2. Entry Data', 'es-ES': '2. Datos de la Entrada', 'fr-FR': '2. Données de l\'Entrée' },
  amountEarned: { 'pt-BR': 'Valor Ganho (R$)', 'en-US': 'Amount Earned (R$)', 'es-ES': 'Valor Ganado (R$)', 'fr-FR': 'Montant Gagné (R$)' },
  tripsCount: { 'pt-BR': 'Viagens', 'en-US': 'Trips', 'es-ES': 'Viajes', 'fr-FR': 'Voyages' },
  addedEntries: { 'pt-BR': 'Lançamentos Adicionados', 'en-US': 'Added Entries', 'es-ES': 'Entradas Añadidas', 'fr-FR': 'Entrées Ajoutées' },
  item: { 'pt-BR': 'Item', 'en-US': 'Item', 'es-ES': 'Artículo', 'fr-FR': 'Article' },
  items: { 'pt-BR': 'Itens', 'en-US': 'Items', 'es-ES': 'Artículos', 'fr-FR': 'Articles' },
  speechRecognitionError: { 'pt-BR': 'Erro no reconhecimento de voz', 'en-US': 'Speech recognition error', 'es-ES': 'Error en reconhecimento de voz', 'fr-FR': 'Erreur de reconnaissance vocale' },
  couldNotParseVoice: { 'pt-BR': 'Não entendi o comando. Tente algo como "Cinquenta reais de gasolina hoje"', 'en-US': 'Could not understand command. Try something like "Fifty dollars of gas today"', 'es-ES': 'No se entendió el comando. Intenta algo como "Cincuenta pesos de gasolina hoy"', 'fr-FR': 'Impossible de comprendre la commande. Essayez quelque chose como "Cinquante euros d\'essence aujourd\'hui"' },
  voiceProcessingError: { 'pt-BR': 'Erro ao processar áudio', 'en-US': 'Error processing audio', 'es-ES': 'Error al procesar audio', 'fr-FR': 'Erreur lors du traitement audio' },
  microphoneAccessDenied: { 'pt-BR': 'Acesso ao microfone negado. Tente abrir o app em uma nova aba.', 'en-US': 'Microphone access denied. Try opening the app in a new tab.', 'es-ES': 'Acceso al micrófono denegado. Intente abrir la aplicación en una nueva pestaña.', 'fr-FR': 'Accès au microphone refusé. Essayez d\'ouvrir l\'application dans um nouvel onglet.' },
  speechNotSupported: { 'pt-BR': 'Navegador não suporta voz', 'en-US': 'Browser does not support voice', 'es-ES': 'El navegador no soporta voz', 'fr-FR': 'Le navigateur ne supporte pas la voix' },
  speechNotSupportedTitle: { 'pt-BR': 'Voz Não Suportada', 'en-US': 'Voice Not Supported', 'es-ES': 'Voz no Soportada', 'fr-FR': 'Voix non Supportée' },
  speechNotSupportedDesc: { 'pt-BR': 'Seu navegador atual não suporta esta funcionalidade. Tente usar o Google Chrome ou Safari.', 'en-US': 'Your current browser does not support this feature. Try using Google Chrome or Safari.', 'es-ES': 'Su navegador actual no admite esta función. Pruebe con Google Chrome o Safari.', 'fr-FR': 'Votre navigateur actuel ne prend pas en charge cette fonctionnalité. Essayez d\'utiliser Google Chrome ou Safari.' },
  openInNewTab: { 'pt-BR': 'Abrir em Nova Aba', 'en-US': 'Open in New Tab', 'es-ES': 'Abrir en Nueva Pestaña', 'fr-FR': 'Ouvrir dans um Nouvel Onglet' },
  holdToSpeakTitle: { 'pt-BR': 'Toque e Segure', 'en-US': 'Tap and Hold', 'es-ES': 'Toque y Mantenga', 'fr-FR': 'Appuyez et Maintenez' },
  startVoice: { 'pt-BR': 'Iniciar Voz', 'en-US': 'Start Voice', 'es-ES': 'Iniciar Voz', 'fr-FR': 'Démarrer la Voix' },
  stopVoice: { 'pt-BR': 'Parar Voz', 'en-US': 'Stop Voice', 'es-ES': 'Detener Voz', 'fr-FR': 'Arrêter la Voix' },
  listening: { 'pt-BR': 'Ouvindo...', 'en-US': 'Listening...', 'es-ES': 'Escuchando...', 'fr-FR': 'Écoute...' },
  processing: { 'pt-BR': 'Processando...', 'en-US': 'Processing...', 'es-ES': 'Procesando...', 'fr-FR': 'Traitement...' },
  aiProcessingAudio: { 'pt-BR': 'IA analisando áudio...', 'en-US': 'AI analyzing audio...', 'es-ES': 'IA analizando audio...', 'fr-FR': 'IA analýse l\'audio...' },
  addByVoice: { 'pt-BR': 'Lançamento por Voz', 'en-US': 'Voice Entry', 'es-ES': 'Entrada por Voz', 'fr-FR': 'Entrée Vocale' },
  voiceEntryPTTPrompt: { 'pt-BR': 'Segure o botão abaixo para falar o que deseja registrar.', 'en-US': 'Hold the button below to speak what you want to record.', 'es-ES': 'Mantenga presionado el botón de abajo para decir o que deseja registrar.', 'fr-FR': 'Maintenez le bouton ci-dessous pour dire ce que vous souhaitez enregistrer.' },
  holdToSpeak: { 'pt-BR': 'Segure para falar', 'en-US': 'Hold to speak', 'es-ES': 'Mantener para hablar', 'fr-FR': 'Maintenir pour parler' },
  holdToSpeakText: { 'pt-BR': 'Segure o botão para falar', 'en-US': 'Hold the button to speak', 'es-ES': 'Mantenga el botón para hablar', 'fr-FR': 'Maintenez le bouton pour parler' },
  saySomethingLike: { 'pt-BR': 'Fale agora...', 'en-US': 'Speak now...', 'es-ES': 'Habla ahora...', 'fr-FR': 'Parlez maintenant...' },
  expenseVoiceExample: { 
    'pt-BR': '"Gastei 150 reais de gasolina, 5,50 o litro, tanque cheio"', 
    'en-US': '"Spent 100 dollars on gas, 5.50 per liter, full tank"', 
    'es-ES': '"Gasté 150 pesos de gasolina, 5,50 el litro, tanque lleno"', 
    'fr-FR': '"Dépensé 150 euros d\'essence, 5,50 le litre, plein fait"' 
  },
  incomeVoiceExample: { 
    'pt-BR': '"Ganhei 350 reais na Uber hoje em 8 horas e rodei 120 km"', 
    'en-US': '"I earned 350 dollars on Uber today in 8 hours and drove 120 km"', 
    'es-ES': '"Ganó 350 pesos en Uber hoy en 8 horas y manejé 120 km"', 
    'fr-FR': '"J\'ai gagné 350 euros sur Uber aujourd\'hui en 8 heures et j\'ai conduit 120 km"' 
  },
  calculatorVoiceExample: { 'pt-BR': '"O álcool está 3,89 e a gasolina 5,65"', 'en-US': '"Ethanol is 3.89 and gas is 5.65"', 'es-ES': '"El alcohol está a 3,89 y la gasolina a 5,65"', 'fr-FR': '"L\'éthanol est à 3,89 e l\'essence est à 5,65"' },
  tripsLower: { 'pt-BR': 'viagens', 'en-US': 'trips', 'es-ES': 'viajes', 'fr-FR': 'voyages' },
  subtotal: { 'pt-BR': 'Subtotal', 'en-US': 'Subtotal', 'es-ES': 'Subtotal', 'fr-FR': 'Sous-total' },
  noEntriesAdded: { 'pt-BR': 'Nenhum lançamento adicionado', 'en-US': 'No entries added', 'es-ES': 'No se han añadido entradas', 'fr-FR': 'Aucune entrée ajoutée' },
  accumulatedTotal: { 'pt-BR': 'Total Acumulado', 'en-US': 'Accumulated Total', 'es-ES': 'Total Acumulado', 'fr-FR': 'Total Accumulé' },
  updateIncome: { 'pt-BR': 'Atualizar Ganho', 'en-US': 'Update Income', 'es-ES': 'Actualizar Ingreso', 'fr-FR': 'Mettre à jour le Revenu' },
  records: { 'pt-BR': 'registros', 'en-US': 'records', 'es-ES': 'registros', 'fr-FR': 'enregistrements' },
  expenseRegisteredSuccess: { 'pt-BR': 'Gasto registrado com sucesso!', 'en-US': 'Expense registered successfully!', 'es-ES': '¡Gasto registrado con éxito!', 'fr-FR': 'Dépense enregistrée avec succès !' },
  expenseAmount: { 'pt-BR': 'Valor do Gasto', 'en-US': 'Expense Amount', 'es-ES': 'Valor del Gasto', 'fr-FR': 'Montant de la Dépense' },
  fuelType: { 'pt-BR': 'Tipo de Combustível', 'en-US': 'Fuel Type', 'es-ES': 'Tipo de Combustible', 'fr-FR': 'Type de Carburant' },
  maintenanceType: { 'pt-BR': 'Tipo de Manutenção', 'en-US': 'Maintenance Type', 'es-ES': 'Tipo de Mantenimiento', 'fr-FR': 'Type d\'Entretien' },
  foodType: { 'pt-BR': 'Tipo de Alimentação', 'en-US': 'Food Type', 'es-ES': 'Tipo de Alimentación', 'fr-FR': 'Type d\'Alimentation' },
  fuelDetails: { 'pt-BR': 'Detalhes de Abastecimento', 'en-US': 'Fueling Details', 'es-ES': 'Detalles de Abastecimiento', 'fr-FR': 'Détails du Ravitaillement' },
  fuelExpense: { 'pt-BR': 'Gasto com Combustível', 'en-US': 'Fuel Expense', 'es-ES': 'Gasto en Combustible', 'fr-FR': 'Dépense de Carburant' },
  saveChanges: { 'pt-BR': 'Salvar Alterações', 'en-US': 'Save Changes', 'es-ES': 'Guardar Cambios', 'fr-FR': 'Enregistrer les Modifications' },
  fillRequiredFields: { 'pt-BR': 'Por favor, preencha todos os campos obrigatórios.', 'en-US': 'Please fill in all required fields.', 'es-ES': 'Por favor, complete todos los campos obligatorios.', 'fr-FR': 'Veuillez remplir tous les champs obligatoires.' },
  odometerRequired: { 'pt-BR': 'O campo odômetro é obrigatório para abastecimentos.', 'en-US': 'Odometer field is required for fueling.', 'es-ES': 'El campo odómetro é obligatorio para abastecimientos.', 'fr-FR': 'Le champ odomètre est obligatoire pour les ravitaillements.' },
  analyzePerformance: { 'pt-BR': 'Analise seu desempenho financeiro com dados detalhados.', 'en-US': 'Analyze your financial performance with detailed data.', 'es-ES': 'Analice su desempeño financiero con datos detallados.', 'fr-FR': 'Analysez vos performances financières avec des données détaillées.' },
  profit: { 'pt-BR': 'Lucro', 'en-US': 'Profit', 'es-ES': 'Beneficio', 'fr-FR': 'Bénéfice' },
  earnings: { 'pt-BR': 'Ganhos', 'en-US': 'Earnings', 'es-ES': 'Ingresos', 'fr-FR': 'Gains' },
  expenses: { 'pt-BR': 'Gastos', 'en-US': 'Expenses', 'es-ES': 'Gastos', 'fr-FR': 'Dépenses' },
  from: { 'pt-BR': 'De', 'en-US': 'From', 'es-ES': 'De', 'fr-FR': 'De' },
  to: { 'pt-BR': 'Até', 'en-US': 'To', 'es-ES': 'Hasta', 'fr-FR': 'À' },
  chartActivityNotice: { 'pt-BR': 'Os gráficos mostram apenas as datas em que houve atividade.', 'en-US': 'Charts show only dates with activity.', 'es-ES': 'Los gráficos muestran solo las fechas con actividad.', 'fr-FR': 'Les graphiques ne montrent que les dates avec activité.' },
  noChartData: { 'pt-BR': 'Sem dados para exibir o gráfico', 'en-US': 'No data to display chart', 'es-ES': 'Sin datos para mostrar el gráfico', 'fr-FR': 'Aucune donnée pour afficher le graphique' },
  detailedStats: { 'pt-BR': 'Estatísticas Detalhadas', 'en-US': 'Detailed Statistics', 'es-ES': 'Estadísticas Detalladas', 'fr-FR': 'Statistiques Détaillées' },
  financialSummary: { 'pt-BR': 'Resumo Financeiro', 'en-US': 'Financial Summary', 'es-ES': 'Resumen Financiero', 'fr-FR': 'Résumé Financier' },
  earningsProfitByPlatform: { 'pt-BR': 'Ganhos e Lucros por Plataforma', 'en-US': 'Earnings and Profits by Platform', 'es-ES': 'Ingresos y Beneficios por Plataforma', 'fr-FR': 'Gains et Bénéfices par Plateforme' },
  expensesByCategory: { 'pt-BR': 'Gastos por Categoria' , 'en-US': 'Expenses by Category', 'es-ES': 'Gastos por Categoría', 'fr-FR': 'Dépenses par Catégorie' },
  all: { 'pt-BR': 'Tudo', 'en-US': 'All', 'es-ES': 'Todo', 'fr-FR': 'Tout' },
  totalTrips: { 'pt-BR': 'Viagens Totais', 'en-US': 'Total Trips', 'es-ES': 'Viajes Totales', 'fr-FR': 'Total des Voyages' },
  profitPerTrip: { 'pt-BR': 'Lucro / Viagem', 'en-US': 'Profit / Trip', 'es-ES': 'Beneficio / Viaje', 'fr-FR': 'Bénéfice / Voyage' },
  profitPerKm: { 'pt-BR': 'Lucro / KM', 'en-US': 'Profit / KM', 'es-ES': 'Beneficio / KM', 'fr-FR': 'Bénéfice / KM' },
  profitPerHour: { 'pt-BR': 'Lucro / Hora', 'en-US': 'Profit / Hour', 'es-ES': 'Beneficio / Hora', 'fr-FR': 'Bénéfice / Heure' },
  earningPerTrip: { 'pt-BR': 'Ganho / Viagem', 'en-US': 'Earning / Trip', 'es-ES': 'Ingreso / Viaje', 'fr-FR': 'Gain / Voyage' },
  earningPerKm: { 'pt-BR': 'Ganho / KM', 'en-US': 'Earning / KM', 'es-ES': 'Ingreso / KM', 'fr-FR': 'Gain / KM' },
  earningPerHour: { 'pt-BR': 'Ganho / Hora', 'en-US': 'Earning / Hour', 'es-ES': 'Ingreso / Hora', 'fr-FR': 'Gain / Heure' },
  expensePerTrip: { 'pt-BR': 'Gasto / Viagem', 'en-US': 'Expense / Trip', 'es-ES': 'Gasto / Viaje', 'fr-FR': 'Dépense / Voyage' },
  expensePerKm: { 'pt-BR': 'Gasto / KM', 'en-US': 'Expense / KM', 'es-ES': 'Gasto / KM', 'fr-FR': 'Dépense / KM' },
  expensePerHour: { 'pt-BR': 'Gasto / Hora', 'en-US': 'Expense / Hour', 'es-ES': 'Gasto / Hora', 'fr-FR': 'Dépense / Heure' },
  cancelEdition: { 'pt-BR': 'Cancelar Edição', 'en-US': 'Cancel Edition', 'es-ES': 'Cancelar Edición', 'fr-FR': 'Annuler l\'Édition' },
  addAtLeastOneEntry: { 'pt-BR': 'Adicione pelo menos um lançamento antes de confirmar.', 'en-US': 'Add at least one entry before confirming.', 'es-ES': 'Añada al menos una entrada antes de confirmar.', 'fr-FR': 'Ajoutez au moins une entrée avant de confirmer.' },
  enterExpenseAmount: { 'pt-BR': 'Insira um valor para o gasto.', 'en-US': 'Enter an amount for the expense.', 'es-ES': 'Ingrese un valor para el gasto.', 'fr-FR': 'Entrez un montant pour la dépense.' },
  notesPlaceholder: { 
    'pt-BR': 'Anote detalhes ou descreva aqui...', 
    'en-US': 'Note details or describe here...', 
    'es-ES': 'Anote detalhes o descreva aquí...', 
    'fr-FR': 'Notez les détails ou décrivez ici...' 
  },
  expenseNotesPlaceholder: { 
    'pt-BR': 'Anote detalhes ou descreva aqui...', 
    'en-US': 'Note details or describe here...', 
    'es-ES': 'Anote detalhes o descreva aqui...', 
    'fr-FR': 'Notez les détails ou décrivez ici...' 
  },
  totalAccumulated: { 'pt-BR': 'Total Acumulado', 'en-US': 'Total Accumulated', 'es-ES': 'Total Acumulado', 'fr-FR': 'Total Accumulé' },
  earningsUpper: { 'pt-BR': 'GANHOS', 'en-US': 'EARNINGS', 'es-ES': 'INGRESOS', 'fr-FR': 'GAINS' },
  profitUpper: { 'pt-BR': 'LUCRO', 'en-US': 'PROFIT', 'es-ES': 'BENEFICIO', 'fr-FR': 'BÉNÉFICE' },
  ofTotal: { 'pt-BR': 'do gasto total', 'en-US': 'of total expense', 'es-ES': 'del gasto total', 'fr-FR': 'de la dépense totale' },
  ofGrossEarnings: { 'pt-BR': 'do ganho bruto', 'en-US': 'of gross earnings', 'es-ES': 'del ingreso bruto', 'fr-FR': 'du gain brut' },
  noEarningsByPlatform: { 'pt-BR': 'Nenhum ganho registrado por plataforma', 'en-US': 'No earnings recorded by platform', 'es-ES': 'No hay ingresos registrados por plataforma', 'fr-FR': 'Aucun gain enregistré par plateforme' },
  noExpensesByCategory: { 'pt-BR': 'Nenhum gasto registrado por categoria', 'en-US': 'No expenses recorded by category', 'es-ES': 'No hay gastos registrados por categoría', 'fr-FR': 'Aucune dépense enregistrée par catégorie' },
  earningUpper: { 'pt-BR': 'GANHO', 'en-US': 'EARNING', 'es-ES': 'INGRESO', 'fr-FR': 'GAIN' },
  overview: { 'pt-BR': 'Visão Geral', 'en-US': 'Overview', 'es-ES': 'Visión General', 'fr-FR': 'Vue d\'ensemble' },
  day: { 'pt-BR': 'Dia', 'en-US': 'Day', 'es-ES': 'Día', 'fr-FR': 'Jour' },
  week: { 'pt-BR': 'Semana', 'en-US': 'Week', 'es-ES': 'Semana', 'fr-FR': 'Semaine' },
  month: { 'pt-BR': 'Mês', 'en-US': 'Month', 'es-ES': 'Mes', 'fr-FR': 'Mois' },
  year: { 'pt-BR': 'Ano', 'en-US': 'Year', 'es-ES': 'Año', 'fr-FR': 'An' },
  completed: { 'pt-BR': 'Concluído', 'en-US': 'Completed', 'es-ES': 'Completado', 'fr-FR': 'Terminé' },
  goalReached: { 'pt-BR': 'Você atingiu', 'en-US': 'You reached', 'es-ES': 'Has alcanzado', 'fr-FR': 'Vous avez atteint' },
  ofYourGoalOf: { 'pt-BR': 'da sua meta de', 'en-US': 'of your goal of', 'es-ES': 'de su meta de', 'fr-FR': 'de votre objectif de' },
  leftToHitGoal: { 'pt-BR': 'Faltam {amount} para bater a meta!', 'en-US': '{amount} left to hit the goal!', 'es-ES': '¡Faltan {amount} para alcanzar la meta!', 'fr-FR': 'Il reste {amount} pour atteindre l\'objectif !' },
  goalHit: { 'pt-BR': 'Meta batida! Parabéns! 🎉', 'en-US': 'Goal hit! Congratulations! 🎉', 'es-ES': '¡Meta alcanzada! ¡Felicidades! 🎉', 'fr-FR': 'Objectif atteint ! Félicitations ! 🎉' },
  goalExceeded: { 
    'pt-BR': 'Você superou a meta em {amount} ({percent}%)', 
    'en-US': 'You exceeded the goal by {amount} ({percent}%)',
    'es-ES': 'Has superado la meta en {amount} ({percent}%)',
    'fr-FR': 'Vous avez dépassé l\'objectif de {amount} ({percent}%)'
  },
  manageAccount: { 'pt-BR': 'Gerencie sua conta e preferências.', 'en-US': 'Manage your account and preferences.', 'es-ES': 'Gestione su cuenta y preferencias.', 'fr-FR': 'Gérez votre compte et vos préférences.' },
  yourName: { 'pt-BR': 'Seu Nome', 'en-US': 'Your Name', 'es-ES': 'Su Nombre', 'fr-FR': 'Votre Nom' },
  saveProfile: { 'pt-BR': 'Salvar Perfil', 'en-US': 'Save Profile', 'es-ES': 'Guardar Perfil', 'fr-FR': 'Enregistrer le Profil' },
  goalSettings: { 'pt-BR': 'Configurações de Metas', 'en-US': 'Goal Settings', 'es-ES': 'Configuración de Metas', 'fr-FR': 'Paramètres d\'Objectif' },
  monthlyProfit: { 'pt-BR': 'Lucro Mensal (R$)', 'en-US': 'Monthly Profit (R$)', 'es-ES': 'Beneficio Mensual (R$)', 'fr-FR': 'Bénéfice Mensuel (R$)' },
  dailyProfit: { 'pt-BR': 'Lucro Diário', 'en-US': 'Daily Profit', 'es-ES': 'Beneficio Diario', 'fr-FR': 'Bénéfice Quotidien' },
  weeklyProfit: { 'pt-BR': 'Lucro Semanal', 'en-US': 'Weekly Profit', 'es-ES': 'Beneficio Semanal', 'fr-FR': 'Bénéfice Hebdomadaire' },
  yearlyProfit: { 'pt-BR': 'Lucro Anual', 'en-US': 'Yearly Profit', 'es-ES': 'Beneficio Anual', 'fr-FR': 'Bénéfice Annuel' },
  goalInfo: { 
    'pt-BR': 'Para alcançar seu lucro mensal de {monthly}, seu lucro médio por hora deve ser de {hourly} (considerando {hours}h de trabalho diário).', 
    'en-US': 'To reach your monthly profit of {monthly}, your average profit per hour should be {hourly} (assuming {hours}h of daily work).',
    'es-ES': 'Para alcanzar su beneficio mensual de {monthly}, su beneficio promedio por hora debe ser de {hourly} (asumiendo {hours}h de trabajo diario).',
    'fr-FR': 'Pour atteindre votre bénéfice mensuel de {monthly}, votre bénéfice moyen par heure devrait être de {hourly} (en supposant {hours}h de travail quotidien).'
  },
  saveGoal: { 'pt-BR': 'Salvar Meta', 'en-US': 'Save Goal', 'es-ES': 'Guardar Meta', 'fr-FR': 'Enregistrer l\'Objectif' },
  darkModeDesc: { 'pt-BR': 'Ideal para turnos noturnos.', 'en-US': 'Ideal for night shifts.', 'es-ES': 'Ideal para turnos nocturnos.', 'fr-FR': 'Idéal pour les équipes de nuit.' },
  languageDesc: { 'pt-BR': 'Interface e suporte.', 'en-US': 'Interface and support.', 'es-ES': 'Interfaz y soporte.', 'fr-FR': 'Interface et support.' },
  developedFor: { 'pt-BR': 'Desenvolvido para profissionais da mobilidade urbana.', 'en-US': 'Developed for urban mobility professionals.', 'es-ES': 'Desarrollado para profesionales de la movilidad urbana.', 'fr-FR': 'Développé pour les professionnels de la mobilité urbaine.' },
  logout: { 'pt-BR': 'Sair', 'en-US': 'Logout', 'es-ES': 'Cerrar sesión', 'fr-FR': 'Déconnexion' },
  // Fuel Types
  gasoline: { 'pt-BR': 'Gasolina', 'en-US': 'Gasoline', 'es-ES': 'Gasolina', 'fr-FR': 'Essence' },
  // Maintenance Types
  seatBelt: { 'pt-BR': 'Cinto', 'en-US': 'Seat Belt', 'es-ES': 'Cinturón', 'fr-FR': 'Ceinture de Sécurité' },
  belt: { 'pt-BR': 'Correia', 'en-US': 'Belt', 'es-ES': 'Correa', 'fr-FR': 'Courroie' },
  windshieldWipers: { 'pt-BR': 'Limpadores de Parabrisas', 'en-US': 'Windshield Wipers', 'es-ES': 'Limpiaparabrisas', 'fr-FR': 'Essuie-glaces' },
  lights: { 'pt-BR': 'Luzes', 'en-US': 'Lights', 'es-ES': 'Luces', 'fr-FR': 'Feux' },
  tires: { 'pt-BR': 'Pneus', 'en-US': 'Tires', 'es-ES': 'Neumáticos', 'fr-FR': 'Pneus' },
  changeDate: { 'pt-BR': 'Alterar Período', 'en-US': 'Change Period', 'es-ES': 'Cambiar Período', 'fr-FR': 'Changer la Période' },
  periodAnalysis: { 'pt-BR': 'Análise de Período', 'en-US': 'Period Analysis', 'es-ES': 'Análisis de Período', 'fr-FR': 'Analyse de Période' },
  safe: { 'pt-BR': 'Seguro', 'en-US': 'Safe', 'es-ES': 'Seguro', 'fr-FR': 'Sûr' },
  attention: { 'pt-BR': 'Atenção', 'en-US': 'Attention', 'es-ES': 'Atención', 'fr-FR': 'Attention' },
  critical: { 'pt-BR': 'Crítico', 'en-US': 'Critical', 'es-ES': 'Crítico', 'fr-FR': 'Critique' },
  windows: { 'pt-BR': 'Vidros', 'en-US': 'Windows', 'es-ES': 'Ventanillas', 'fr-FR': 'Vitres' },
  // Platform IDs
  fixedIncome: { 'pt-BR': 'Salário / Fixo', 'en-US': 'Salary / Fixed', 'es-ES': 'Salario / Fijo', 'fr-FR': 'Salaire / Fixe' },
  cubicMeters: { 'pt-BR': 'm³', 'en-US': 'ft³', 'es-ES': 'm³', 'fr-FR': 'm³' },
  perLiter: { 'pt-BR': '/L', 'en-US': '/GAL', 'es-ES': '/L', 'fr-FR': '/L' },
  perCubicMeter: { 'pt-BR': '/m³', 'en-US': '/ft³', 'es-ES': '/m³', 'fr-FR': '/m³' },
  currencySymbol: { 'pt-BR': 'R$', 'en-US': '$', 'es-ES': '$', 'fr-FR': '€' },
  diamondPlan: { 'pt-BR': 'Plano Diamante', 'en-US': 'Diamond Plan', 'es-ES': 'Plan Diamante', 'fr-FR': 'Plan Diamant' },
  emailPlaceholder: { 'pt-BR': 'exemplo@email.com', 'en-US': 'example@email.com', 'es-ES': 'ejemplo@email.com', 'fr-FR': 'exemple@email.com' },
  phonePlaceholder: { 'pt-BR': '+55 (11) 99999-9999', 'en-US': '+1 (555) 000-0000', 'es-ES': '+34 600 000 000', 'fr-FR': '+33 6 00 00 00 00' },
  decimalSeparator: { 'pt-BR': ',', 'en-US': '.', 'es-ES': ',', 'fr-FR': ',' },
  hoursUnit: { 'pt-BR': 'h/m', 'en-US': 'h/m', 'es-ES': 'h/m', 'fr-FR': 'h/m' },
  currencyPlaceholder: { 'pt-BR': '0,00', 'en-US': '0.00', 'es-ES': '0,00', 'fr-FR': '0,00' },
  defaultUserName: { 'pt-BR': 'Usuário', 'en-US': 'User', 'es-ES': 'Usuario', 'fr-FR': 'Utilisateur' },
  faqQ1: { 'pt-BR': 'Como o lucro real é calculado?', 'en-US': 'How is real profit calculated?', 'es-ES': '¿Cómo se calcula el beneficio real?', 'fr-FR': 'Comment le bénéfice réel est-il calculé ?' },
  faqA1: { 'pt-BR': 'O lucro real é a soma de todos os seus ganhos brutos menos todas as despesas registradas no período selecionado.', 'en-US': 'Real profit is the sum of all your gross earnings minus all expenses recorded in the selected period.', 'es-ES': 'O lucro real é a soma de todos os seus ganhos brutos menos todas as despesas registradas no período selecionado.', 'fr-FR': 'Le bénéfice réel est a soma de todos os seus ganhos brutos menos todas as despesas registradas no período selecionado.' },
  faqQ2: { 'pt-BR': 'Como altero minha meta mensal?', 'en-US': 'How do I change my monthly goal?', 'es-ES': '¿Cómo cambio mi meta mensual?', 'fr-FR': 'Comment changer mon objectif mensuel ?' },
  faqA2: { 'pt-BR': 'Vá em Ajustes > Configurações de Metas, insira o novo valor no campo "Lucro Mensal" e clique em "Salvar Meta".', 'en-US': 'Go to Settings > Goal Settings, enter the new value in the "Monthly Profit" field and click "Save Goal".', 'es-ES': 'Vá em Ajustes > Configurações de Metas, insira o novo valor no campo "Lucro Mensal" e clique em "Salvar Meta".', 'fr-FR': 'Vá em Ajustes > Configurações de Metas, insira o novo valor no campo "Lucro Mensal" e clique em "Salvar Meta".' },
  faqQ3: { 'pt-BR': 'Meus dados estão seguros?', 'en-US': 'Is my data safe?', 'es-ES': '¿Estão seguros meus dados?', 'fr-FR': 'Mes données sont-elles en sécurité ?' },
  faqA3: { 'pt-BR': 'Sim, todos os seus dados são armazenados localmente no seu dispositivo e não são compartilhados com terceiros.', 'en-US': 'Yes, all your data is stored locally on your device and is not shared with third parties.', 'es-ES': 'Sim, todos os seus dados são armazenados localmente no seu dispositivo e não são compartilhados com terceiros.', 'fr-FR': 'Sim, todos os seus dados são armazenados localmente no seu dispositivo e não são compartilhados com terceiros.' },
  faqQ4: { 'pt-BR': 'Como exportar relatórios?', 'en-US': 'How to export reports?', 'es-ES': '¿Cómo exportar informes?', 'fr-FR': 'Comment exporter des rapports ?' },
  faqA4: { 'pt-BR': 'Você pode exportar seus relatórios na tela de Relatórios, selecionando o período desejado e clicando no botão "Exportar". Estão disponíveis os formatos PDF, Excel e CSV.', 'en-US': 'You can export your reports on the Reports screen by selecting the desired period and clicking the "Export" button. PDF, Excel, and CSV formats are available.', 'es-ES': 'Você pode exportar seus relatórios na tela de Relatórios, selecionando o período desejado e clicando no botão "Exportar". Estão disponíveis os formatos PDF, Excel e CSV.', 'fr-FR': 'Vous pouvez exportar seus relatórios na tela de Relatórios, selecionando o período desejado e clicando no botão "Exportar". Estão disponíveis os formatos PDF, Excel e CSV.' },
  export: { 'pt-BR': 'Exportar', 'en-US': 'Export', 'es-ES': 'Exportar', 'fr-FR': 'Exporter' },
  exportPdf: { 'pt-BR': 'Exportar PDF', 'en-US': 'Export PDF', 'es-ES': 'Exportar PDF', 'fr-FR': 'Exporter PDF' },
  exportExcel: { 'pt-BR': 'Exportar Excel', 'en-US': 'Export Excel', 'es-ES': 'Exportar Excel', 'fr-FR': 'Exporter Excel' },
  exportCsv: { 'pt-BR': 'Exportar CSV', 'en-US': 'Export CSV', 'es-ES': 'Exportar CSV', 'fr-FR': 'Exporter CSV' },
  reportTitle: { 'pt-BR': 'Relatório de Atividade', 'en-US': 'Activity Report', 'es-ES': 'Informe de Actividad', 'fr-FR': 'Rapport d\'Activité' },
  dangerZone: { 'pt-BR': 'Zona de Perigo', 'en-US': 'Danger Zone', 'es-ES': 'Zona de Peligro', 'fr-FR': 'Zone de Danger' },
  clearAllData: { 'pt-BR': 'Apagar Tudo', 'en-US': 'Clear All Data', 'es-ES': 'Borrar Todo', 'fr-FR': 'Tout Effacer' },
  clearAllDataTitle: { 'pt-BR': 'Apagar todos os registros', 'en-US': 'Clear all records', 'es-ES': 'Borrar todos los registros', 'fr-FR': 'Effacer tous les enregistrements' },
  clearAllDataDesc: { 'pt-BR': 'Esta ação irá remover permanentemente todos os seus ganhos e gastos registrados. Esta ação não pode ser desfeita.', 'en-US': 'This action will permanently remove all your recorded earnings and expenses. This action cannot be undone.', 'es-ES': 'Esta acción eliminará permanentemente todos sus ingresos y gastos registrados. Esta acción no se puede deshacer.', 'fr-FR': 'Cette action supprimera définitivement tous vos revenus et dépenses enregistrés. Cette action est irréversible.' },
  confirmClearAllData: { 'pt-BR': 'Tem certeza que deseja apagar TODOS os seus dados? Esta ação é permanente.', 'en-US': 'Are you sure you want to clear ALL your data? This action is permanent.', 'es-ES': '¿Está seguro de que desea borrar TODOS sus datos? Esta acción es permanente.', 'fr-FR': 'Êtes-vous sûr de vouloir effacer TOUTES vos données ? Cette action est permanente.' },
  ratio: { 'pt-BR': 'Relação', 'en-US': 'Ratio', 'es-ES': 'Relación', 'fr-FR': 'Rapport' },
  attachment: { 'pt-BR': 'Anexo', 'en-US': 'Attachment', 'es-ES': 'Adjunto', 'fr-FR': 'Pièce jointe' },
  addAttachment: { 'pt-BR': 'Adicionar Anexo', 'en-US': 'Add Attachment', 'es-ES': 'Añadir Adjunto', 'fr-FR': 'Ajouter une Pièce Jointe' },
  addAttachmentDesc: { 'pt-BR': 'Adicione uma foto do recibo ou comprovante.', 'en-US': 'Add a photo of the receipt or proof.', 'es-ES': 'Añada una foto del recibo o comprobante.', 'fr-FR': 'Ajoutez une photo du reçu ou du justificatif.' },
  attachmentAdded: { 'pt-BR': 'Anexo adicionado com sucesso!', 'en-US': 'Attachment added successfully!', 'es-ES': '¡Adjunto añadido con éxito!', 'fr-FR': 'Pièce jointe ajoutée avec succès !' },
  loadMockDataDesc: { 'pt-BR': 'Preenche o aplicativo com dados fictícios para teste das funcionalidades.', 'en-US': 'Fills the app with dummy data to test features.', 'es-ES': 'Llena la aplicación con datos ficticios para probar las funciones.', 'fr-FR': 'Remplit l\'application avec des données fictives pour tester les fonctionnalités.' },
  confirmLoadMockData: { 'pt-BR': 'Deseja carregar os dados de demonstração? Isso irá sobrescrever seus dados atuais.', 'en-US': 'Do you want to load demo data? This will overwrite your current data.', 'es-ES': '¿Desea cargar los datos de demostración? Esto sobrescribirá sus datos actuales.', 'fr-FR': 'Voulez-vous charger les données de démonstration ? Cela écrasera vos données actuelles.' },
  ethanolPrice: { 'pt-BR': 'Preço do Etanol (R$)', 'en-US': 'Ethanol Price ($)', 'es-ES': 'Precio del Etanol ($)', 'fr-FR': 'Prix de l\'Éthanol (€)' },
  gasolinePrice: { 'pt-BR': 'Preço da Gasolina (R$)', 'en-US': 'Gasoline Price ($)', 'es-ES': 'Precio de la Gasolina ($)', 'fr-FR': 'Prix de l\'Essence (€)' },
  calculate: { 'pt-BR': 'Calcular', 'en-US': 'Calculate', 'es-ES': 'Calcular', 'fr-FR': 'Calculer' },
  advantageEthanol: { 'pt-BR': 'Abasteça com Etanol!', 'en-US': 'Fill up with Ethanol!', 'es-ES': '¡Abasteça com Etanol!', 'fr-FR': 'Faites le plein d\'Éthanol !' },
  advantageGasoline: { 'pt-BR': 'Abasteça com Gasolina!', 'en-US': 'Fill up with Gasoline!', 'es-ES': '¡Abastezca com Gasolina!', 'fr-FR': 'Faites le plein d\'Essence !' },
  flexRatioInfo: { 'pt-BR': 'O cálculo baseia-se na regra de que o etanol é vantajoso se custar até 70% do preço da gasolina.', 'en-US': 'The calculation is based on the rule that ethanol is advantageous if it costs up to 70% of the gasoline price.', 'es-ES': 'El cálculo se basa en la regra de que el etanol é ventajoso si cuesta até 70% do preço da gasolina.', 'fr-FR': 'Le calcul est baseado sur la règle selon laquelle l\'éthanol est avantageux s\'il coûte até 70 % du prix de l\'essence.' },
  result: { 'pt-BR': 'Resultado', 'en-US': 'Result', 'es-ES': 'Resultado', 'fr-FR': 'Résultat' },
  customRatio: { 'pt-BR': 'Ajustar Eficiência', 'en-US': 'Adjust Efficiency', 'es-ES': 'Ajustar Eficiencia', 'fr-FR': 'Ajuster l\'Efficacité' },
  resetRatio: { 'pt-BR': 'Restaurar Padrão (70%)', 'en-US': 'Reset to Default (70%)', 'es-ES': 'Restaurar Patrón (70%)', 'fr-FR': 'Réinitialiser (70%)' },
  goToFueling: { 'pt-BR': 'Registrar Abastecimento', 'en-US': 'Registrar Abastecimento', 'es-ES': 'Registrar Abastecimiento', 'fr-FR': 'Enregistrer le Ravitaillement' },
  advantageous: { 'pt-BR': 'Vantajoso', 'en-US': 'Advantageous', 'es-ES': 'Ventajoso', 'fr-FR': 'Avantageux' },
  notAdvantageous: { 'pt-BR': 'Não Vantajoso', 'en-US': 'Not Advantageous', 'es-ES': 'No Ventajoso', 'fr-FR': 'Pas Avantageux' },
  fuelSummary: { 'pt-BR': 'Resumo de Abastecimentos', 'en-US': 'Fueling Summary', 'es-ES': 'Resumen de Abastecimiento', 'fr-FR': 'Résumé du Ravitaillement' },
  fuelingCount: { 'pt-BR': 'Qtd. Abastecimentos', 'en-US': 'Fueling Count', 'es-ES': 'Cant. Abastecimientos', 'fr-FR': 'Nombre de Ravitaillements' },
  totalLiters: { 'pt-BR': 'Litros Totais', 'en-US': 'Total Liters', 'es-ES': 'Litros Totales', 'fr-FR': 'Litres Totaux' },
  maxPrice: { 'pt-BR': 'Maior Preço/L', 'en-US': 'Max Price/L', 'es-ES': 'Mayor Precio/L', 'fr-FR': 'Prix Max/L' },
  minPrice: { 'pt-BR': 'Menor Preço/L', 'en-US': 'Min Price/L', 'es-ES': 'Menor Precio/L', 'fr-FR': 'Prix Min/L' },
  fuelProjection: { 'pt-BR': 'Projeção de Abastecimento', 'en-US': 'Fueling Projection', 'es-ES': 'Proyección de Abastecimiento', 'fr-FR': 'Projection de Ravitaillement' },
  pricePerLiterShort: { 'pt-BR': 'Preço/L', 'en-US': 'Price/L', 'es-ES': 'Precio/L', 'fr-FR': 'Prix/L' },
  averageConsumption: { 'pt-BR': 'Média de Consumo', 'en-US': 'Average Consumption', 'es-ES': 'Consumo Promedio', 'fr-FR': 'Consommation Moyenne' },
  returnToToday: { 'pt-BR': 'Retornar ao dia atual', 'en-US': 'Return to today', 'es-ES': 'Volver a hoy', 'fr-FR': 'Retour à aujourd\'hui' },
  returnToCurrentWeek: { 'pt-BR': 'Retornar à semana atual', 'en-US': 'Return to current week', 'es-ES': 'Volver a la semana actual', 'fr-FR': 'Retour à la semaine actuelle' },
  returnToCurrentMonth: { 'pt-BR': 'Retornar ao mês atual', 'en-US': 'Return to current month', 'es-ES': 'Volver al mes atual', 'fr-FR': 'Retour au mois actuel' },
  returnToCurrentYear: { 'pt-BR': 'Retornar ao ano atual', 'en-US': 'Return to current year', 'es-ES': 'Volver al año actual', 'fr-FR': 'Retour à l\'année actuelle' },
  avgPrice: { 'pt-BR': 'Média Preço/L', 'en-US': 'Avg Price/L', 'es-ES': 'Precio Promedio/L', 'fr-FR': 'Prix Moyen/L' },
  performanceByFuel: { 'pt-BR': 'Desempenho de Combustível', 'en-US': 'Fuel Performance', 'es-ES': 'Desempeño de Combustible', 'fr-FR': 'Performance du Carburant' },
  performanceInfo: { 'pt-BR': 'Para calcular o desempenho, são necessários pelo menos dois abastecimentos consecutivos de tanque cheio com o mesmo combustível.', 'en-US': 'To calculate performance, at least two consecutive full-tank refills with the same fuel are required.', 'es-ES': 'Para calcular el desempeño, se requieren al menos dos abastecimientos consecutivos de tanque lleno con el mismo combustible.', 'fr-FR': 'Pour calculer la performance, au moins deux ravitaillements consécutifs avec le plein du même carburant sont nécessaires.' },
  performanceRequirementInfo: { 
    'pt-BR': 'Para Calcular o Desempenho seja de tanque cheio ou Tanque parcial são necessários pelo menos dois abastecimentos consecutivos do mesmo combustível.', 
    'en-US': 'To calculate performance, whether full tank or partial tank, at least two consecutive refuelings of the same fuel are required.', 
    'es-ES': 'Para calcular el rendimiento, ya sea tanque lleno o tanque parcial, se requieren al menos dos abastecimientos consecutivos del mismo combustible.', 
    'fr-FR': 'Pour calculer la performance, qu\'il s\'agisse d\'un réservoir plein ou partiel, au moins deux ravitaillements consécutifs du même carburant sont nécessaires.' 
  },
  gasolineGroupingInfo: { 'pt-BR': 'Diferentes tipos de gasolina são calculados como um único tipo de combustível.', 'en-US': 'Different types of gasoline are calculated as a single fuel type.', 'es-ES': 'Diferentes tipos de gasolina se calculan como un solo tipo de combustible.', 'fr-FR': 'Différents types d\'essence sont calculés como un seul type de carburant.' },
  totalFuelSpent: { 'pt-BR': 'Total Gasto (Período)', 'en-US': 'Total Spent (Period)', 'es-ES': 'Total Gastado (Período)', 'fr-FR': 'Total Dépensé (Période)' },
  totalFuelLiters: { 'pt-BR': 'Total Litros (Período)', 'en-US': 'Total Liters (Period)', 'es-ES': 'Total Litros (Período)', 'fr-FR': 'Total Litres (Période)' },
  averagePrice: { 'pt-BR': 'Preço Médio', 'en-US': 'Average Price', 'es-ES': 'Precio Medio', 'fr-FR': 'Prix Moyen' },
  quantity: { 'pt-BR': 'Qtd.', 'en-US': 'Qty.', 'es-ES': 'Cant.', 'fr-FR': 'Qté.' },
  totalKm: { 'pt-BR': 'KM Total', 'en-US': 'Total KM', 'es-ES': 'KM Total', 'fr-FR': 'KM Total' },
  bestPerformance: { 'pt-BR': 'Melhor Desempenho', 'en-US': 'Best Performance', 'es-ES': 'Mejor Desempeño', 'fr-FR': 'Meilleure Performance' },
  worstPerformance: { 'pt-BR': 'Pior Desempenho', 'en-US': 'Worst Performance', 'es-ES': 'Peor Desempeño', 'fr-FR': 'Pire Performance' },
  lastOdometerLabel: { 'pt-BR': 'Último Km:', 'en-US': 'Last Km:', 'es-ES': 'Último Km:', 'fr-FR': 'Dernier Km :' },
  ignoreGasolineType: { 'pt-BR': 'Ignorar tipo de Gasolina', 'en-US': 'Ignore Gasoline Type', 'es-ES': 'Ignorar tipo de Gasolina', 'fr-FR': 'Ignorer le type d\'Essence' },
  lastRefill: { 'pt-BR': 'Último Abastecimento', 'en-US': 'Last Refill', 'es-ES': 'Último Abastecimiento', 'fr-FR': 'Dernier Ravitaillement' },
   finalSummary: { 'pt-BR': 'Resumo Final', 'en-US': 'Final Summary', 'es-ES': 'Resumen Final', 'fr-FR': 'Résumé Final' },
  reminders: { 'pt-BR': 'Lembretes', 'en-US': 'Reminders', 'es-ES': 'Recordatorios', 'fr-FR': 'Rappels' },
  addReminder: { 'pt-BR': 'Adicionar Lembrete', 'en-US': 'Add Reminder', 'es-ES': 'Agregar Recordatorio', 'fr-FR': 'Ajouter un Rappel' },
  reminderTitle: { 'pt-BR': 'Título do Lembrete', 'en-US': 'Reminder Title', 'es-ES': 'Título del Recordatorio', 'fr-FR': 'Titre du Rappel' },
  notificationChannel: { 'pt-BR': 'Canal de Notificação', 'en-US': 'Notification Channel', 'es-ES': 'Canal de Notificación', 'fr-FR': 'Canal de Notification' },
  kmDrivenTrigger: { 'pt-BR': 'KM Rodado', 'en-US': 'Mileage (KM)', 'es-ES': 'Kilometraje (KM)', 'fr-FR': 'Kilométrage (KM)' },
  remindMeBy: { 'pt-BR': 'Lembrar por', 'en-US': 'Remind by', 'es-ES': 'Recordar por', 'fr-FR': 'Rappeler par' },
  threeDaysBefore: { 'pt-BR': '3 dias antes', 'en-US': '3 dias antes', 'es-ES': '3 días antes', 'fr-FR': '3 jours avant' },
  remindEveryXKm: { 'pt-BR': 'Lembrar a cada (KM)', 'en-US': 'Remind every (KM)', 'es-ES': 'Recordar cada (KM)', 'fr-FR': 'Rappeler tous les (KM)' },
  notifyAtKm: { 'pt-BR': 'Notificar no KM', 'en-US': 'Notify at KM', 'es-ES': 'Notificar en el KM', 'fr-FR': 'Notifier au KM' },
  optional: { 'pt-BR': '(Opcional)', 'en-US': '(Optional)', 'es-ES': '(Opcional)', 'fr-FR': '(Optionnel)' },
  saveReminder: { 'pt-BR': 'Salvar Lembrete', 'en-US': 'Save Reminder', 'es-ES': 'Guardar Recordatorio', 'fr-FR': 'Enregistrer le Rappel' },
  reminderNotificationTitle: { 'pt-BR': 'Lembrete Ativo', 'en-US': 'Active Reminder', 'es-ES': 'Recordatorio Activo', 'fr-FR': 'Rappel Actif' },
  noReminders: { 'pt-BR': 'Nenhum lembrete configurado', 'en-US': 'No reminders configured', 'es-ES': 'Sin recordatorios configurados', 'fr-FR': 'Aucun rappel configuré' },
  subcategoryAlreadyExists: { 'pt-BR': 'Esta subcategoria já existe nesta categoria!', 'en-US': 'This subcategory already exists in this category!', 'es-ES': '¡Esta subcategoría ya existe en esta categoría!', 'fr-FR': 'Cette sous-catégorie existe déjà dans cette catégorie !' },
  platformAlreadyExists: { 'pt-BR': 'Esta plataforma já existe!', 'en-US': 'This platform already exists!', 'es-ES': '¡Esta plataforma ya existe!', 'fr-FR': 'Cette plataforma existe déjà !' },
  marginAnalysis: { 'pt-BR': 'Análise de Margem', 'en-US': 'Margin Analysis', 'es-ES': 'Análisis de Margen', 'fr-FR': 'Analyse de Marge' },
  costAnalysis: { 'pt-BR': 'Análise de Custos', 'en-US': 'Cost Analysis', 'es-ES': 'Análisis de Costos', 'fr-FR': 'Analyse des Coûts' },
  preventive: { 'pt-BR': 'Preventiva', 'en-US': 'Preventive', 'es-ES': 'Preventiva', 'fr-FR': 'Préventive' },
  corrective: { 'pt-BR': 'Corretiva', 'en-US': 'Corretiva', 'es-ES': 'Correctiva', 'fr-FR': 'Corrective' },
  yes: { 'pt-BR': 'Sim', 'en-US': 'Yes', 'es-ES': 'Sí', 'fr-FR': 'Oui' },
  no: { 'pt-BR': 'Não', 'en-US': 'No', 'es-ES': 'No', 'fr-FR': 'Non' },
  inProgress: { 'pt-BR': 'período aberto', 'en-US': 'in progress', 'es-ES': 'en curso', 'fr-FR': 'en cours' },
  closedPeriod: { 'pt-BR': 'período fechado', 'en-US': 'closed period', 'es-ES': 'período cerrado', 'fr-FR': 'période clôturée' },
  fullTankPerformanceExplanation: {
    'pt-BR': 'Para visualizar o cálculo de tanque completo, você precisa de no mínimo dois abastecimentos seguidos com o tanque cheio utilizando o mesmo combustível. Lembre-se que diferentes tipos de gasolinas são reconhecidas como um único combustível.',
    'en-US': 'To view the full tank calculation, you need at least two consecutive full tank refills using the same fuel. Remember that different types of gasoline are recognized as a single fuel type.',
    'es-ES': 'Para ver el cálculo tanque lleno, necesita al menos dos abastecimientos consecutivos tanque lleno con el mismo combustible. Recuerde que os diferentes tipos de gasolinas se reconhecem como um único tipo de combustível.',
    'fr-FR': 'Pour voir le calcul du plein, vous avez besoin d\'au moins deux pleins consécutifs en utilisant le mesmo carburant.'
  },
  partialTankPerformanceExplanation: {
    'pt-BR': 'Para calcular o tanque parcial, é necessário no mínimo um abastecimento de tanque completo (Início), seguido de um ou mais abastecimentos parciais, e finalizando com outro abastecimento de tanque completo (Fim) para fechar o ciclo.',
    'en-US': 'To calculate the partial tank, you need at least one full tank refill (Start), followed by one or more partial refills, and ending with another full tank refill (End) to close the cycle.',
    'es-ES': 'Para calcular el tanque parcial, necesita al menos um abastecimento de tanque lleno (Inicio), seguido de um ou mais abastecimentos parciales, y finalizando com outro abastecimento de tanque lleno (Fin) para cerrar el ciclo.',
    'fr-FR': 'Pour calculer le réservoir partiel, vous avez besoin d\'au menos um abastecimento de tanque completo (Début), suivi d\'un ou plusieurs ravitaillements partiels, et terminant par um outro abastecimento de tanque completo (Fin) para fermer le cycle.'
  },
  breakEvenTitle: { 'pt-BR': 'Preço de Equilíbrio', 'en-US': 'Break-even Price', 'es-ES': 'Precio de Equilibrio', 'fr-FR': 'Prix d\'Équilibre' },
  breakEvenDesc: { 'pt-BR': 'Até este valor o etanol é mais vantajoso.', 'en-US': 'Up to this price ethanol is more advantageous.', 'es-ES': 'Hasta este precio el etanol é mais ventajoso.', 'fr-FR': 'Jusqu\'à ce prix, l\'éthanol est plus avantageux.' },
  smartImport: { 'pt-BR': 'Importação Inteligente', 'en-US': 'Smart Import', 'es-ES': 'Importación Inteligente', 'fr-FR': 'Importation Intelligente' },
  import: { 'pt-BR': 'Importar', 'en-US': 'Import', 'es-ES': 'Importar', 'fr-FR': 'Importer' },
  smartImportDesc: { 
    'pt-BR': 'Envie arquivos (PDF, Excel, CSV) e nossa IA extrairá os dados automaticamente.', 
    'en-US': 'Upload files (PDF, Excel, CSV) and our AI will extract data automatically.',
    'es-ES': 'Suba archivos (PDF, Excel, CSV) y nuestra IA extrairá los datos automáticamente.',
    'fr-FR': 'Téléchargez des fichiers (PDF, Excel, CSV) et notre IA extraira les données automatiquement.'
  },
  dropFilesHere: { 'pt-BR': 'Arraste arquivos aqui ou clique para selecionar', 'en-US': 'Drop files here or click to select', 'es-ES': 'Arrastre archivos aquí o haga clic para seleccionar', 'fr-FR': 'Déposez les fichiers ici ou cliquez pour sélectionner' },
  supportedFormats: { 'pt-BR': 'Formatos suportados: PDF, Excel, CSV', 'en-US': 'Supported formats: PDF, Excel, CSV', 'es-ES': 'Formatos soportados: PDF, Excel, CSV', 'fr-FR': 'Formats supportés : PDF, Excel, CSV' },
  extractingData: { 'pt-BR': 'Extraindo dados...', 'en-US': 'Extracting data...', 'es-ES': 'Extrayendo dados...', 'fr-FR': 'Extraction des données...' },
  reviewExtractedData: { 'pt-BR': 'Revise os dados extraídos', 'en-US': 'Review extracted data', 'es-ES': 'Revise los datos extraídos', 'fr-FR': 'Vérifiez les données extraites' },
  importSuccess: { 'pt-BR': '{count} registros importados com sucesso!', 'en-US': '{count} records imported successfully!', 'es-ES': '¡{count} registros importados con éxito!', 'fr-FR': '{count} enregistrements importés avec succès !' },
  importError: { 'pt-BR': 'Erro ao importar arquivo. Tente novamente.', 'en-US': 'Error importing file. Please try again.', 'es-ES': 'Error al importar el archivo. Inténtelo de nuevo.', 'fr-FR': 'Erreur lors de l\'importation du fichier. Veuillez réessayer.' },
  noDataFound: { 'pt-BR': 'Nenhum dado compatível encontrado no arquivo.', 'en-US': 'No compatible data found in the file.', 'es-ES': 'No se encontraron datos compatibles en el archivo.', 'fr-FR': 'Aucune donnée compatible trouvée dans le fichier.' },
  saveAll: { 'pt-BR': 'Salvar Todos', 'en-US': 'Save All', 'es-ES': 'Guardar Todos', 'fr-FR': 'Tout Enregistrer' },
  useRealEfficiency: { 'pt-BR': 'Usar seu Desempenho Real', 'en-US': 'Use Real Performance', 'es-ES': 'Usar Desempeño Real', 'fr-FR': 'Utiliser la Performance Réelle' },
  realEfficiencyInfo: { 'pt-BR': 'Baseado no histórico do seu carro.', 'en-US': 'Based on your car\'s history.', 'es-ES': 'Basado en el historial de tu coche.', 'fr-FR': 'Basé sur l\'historique de votre voiture.' },
  monthlyTransactions: { 'pt-BR': 'Lançamentos Mensais', 'en-US': 'Monthly Transactions', 'es-ES': 'Entradas Mensuales', 'fr-FR': 'Entrées Mensuelles' },
  classicMode: { 'pt-BR': 'Modo Comum', 'en-US': 'Classic Mode', 'es-ES': 'Modo Común', 'fr-FR': 'Mode Classique' },
  odometerAtService: { 'pt-BR': 'Hodômetro na Revisão', 'en-US': 'Odometer at Service', 'es-ES': 'Odómetro en la Revisión', 'fr-FR': 'Odomètre à l\'Entretien' },
  maintenanceSettings: { 'pt-BR': 'Ajustes de Manutenção', 'en-US': 'Maintenance Settings', 'es-ES': 'Ajustes de Mantenimiento', 'fr-FR': 'Réglages de Maintenance' },
  updateMaintenancePlan: { 'pt-BR': 'Atualizar Plano', 'en-US': 'Update Plan', 'es-ES': 'Actualizar Plan', 'fr-FR': 'Mettre à jour le Plan' },
  maintenancePlanUpdateDesc: { 
    'pt-BR': 'Isso atualizará o hodômetro da última troca no seu plano de manutenção.', 
    'en-US': 'This will update the odometer of the last service in your maintenance plan.',
    'es-ES': 'Isso atualizará el odómetro de la última revisión en su plan de mantenimiento.',
    'fr-FR': 'Cela mettra à jour l\'odomètre du dernier entretien dans votre plan de maintenance.'
  },
  oilChangePlan: { 'pt-BR': 'Plano de Troca de Óleo', 'en-US': 'Oil Change Plan', 'es-ES': 'Plan de Cambio de Aceite', 'fr-FR': 'Plan de Vidange' },
  earlyMaintenance: { 'pt-BR': 'Antecipar', 'en-US': 'Early Maint.', 'es-ES': 'Anticipar', 'fr-FR': 'Anticiper' },
  spending: { 'pt-BR': 'Gasto', 'en-US': 'Spending', 'es-ES': 'Gasto', 'fr-FR': 'Dépense' },
  maintenanceReceipt: { 'pt-BR': 'Comprovante/Recibo', 'en-US': 'Receipt/Proof', 'es-ES': 'Recibo/Comprobante', 'fr-FR': 'Reçu/Justificatif' },
  maintenanceIn: { 'pt-BR': 'Faltam {km} KM', 'en-US': '{km} KM left', 'es-ES': 'Faltan {km} KM', 'fr-FR': 'Manque {km} KM' },
  runningOverdue: { 'pt-BR': 'Atrasada!', 'en-US': 'Overdue!', 'es-ES': '¡Atrasada!', 'fr-FR': 'En retard !' },
  intervalKm: { 'pt-BR': 'Intervalo (KM)', 'en-US': 'Interval (KM)', 'es-ES': 'Intervalo (KM)', 'fr-FR': 'Intervalle (KM)' },
  lastServiceKm: { 'pt-BR': 'Última Troca (KM)', 'en-US': 'Last Service (KM)', 'es-ES': 'Último Cambio (KM)', 'fr-FR': 'Dernier Entretien (KM)' },
  smartMode: { 'pt-BR': 'Modo Inteligente', 'en-US': 'Smart Mode', 'es-ES': 'Modo Inteligente', 'fr-FR': 'Mode Intelligent' },
  suggestedPrice: { 'pt-BR': 'Preços Sugeridos', 'en-US': 'Suggested Prices', 'es-ES': 'Precios Sugeridos', 'fr-FR': 'Prix Suggérés' },
  insufficientFuelData: { 'pt-BR': 'Dados Insuficientes', 'en-US': 'Insufficient Data', 'es-ES': 'Datos Insuficientes', 'fr-FR': 'Données Insuffisantes' },
  insufficientFuelDataDesc: { 
    'pt-BR': 'Para ativar o Modo Inteligente, são necessários no mínimo 2 registros de abastecimentos com resultado de km/L (fechamento de tanque) de Etanol e 2 de Gasolina. Registros sem média de km/L não contam.', 
    'en-US': 'To activate Smart Mode, at least 2 Ethanol and 2 Gasoline records with km/L results (full tank) are required. Records without km/L average do not count.', 
    'es-ES': 'Para activar el Modo Inteligente, se requieren al menos 2 registros de Etanol y 2 de Gasolina con resultados de km/L (tanque lleno). Los registros sin promedio de km/L no cuentan.', 
    'fr-FR': 'Pour activer le Mode Intelligent, au moins 2 enregistrements d\'Éthanol et 2 d\'Essence avec des résultats de km/L (plein) sont nécessaires. Les enregistrements sans moyenne de km/L ne comptent pas.' 
  },
  fuelCalculationMode: { 'pt-BR': 'Dados para o Cálculo', 'en-US': 'Data for Calculation', 'es-ES': 'Datos para el Cálculo', 'fr-FR': 'Données pour le Calcul' },
  allHistory: { 'pt-BR': 'Todo o Histórico', 'en-US': 'Full History', 'es-ES': 'Todo el Historial', 'fr-FR': 'Tout l\'Historique' },
  recentData: { 'pt-BR': 'Dados Recentes', 'en-US': 'Recent Data', 'es-ES': 'Datos Recientes', 'fr-FR': 'Données Récentes' },
  recentDataDesc: { 'pt-BR': 'Usa a média dos últimos 2 abastecimentos.', 'en-US': 'Uses the average of the last 2 refuels.', 'es-ES': 'Usa el promedio de los últimos 2 repostajes.', 'fr-FR': 'Utilise la moyenne des 2 derniers pleins.' },
  smartModeLocked: { 'pt-BR': 'Modo Travado', 'en-US': 'Mode Locked', 'es-ES': 'Modo Bloqueado', 'fr-FR': 'Mode Verrouillé' },
  categoryManagement: { 'pt-BR': 'Gerenciamento de Categorias', 'en-US': 'Category Management', 'es-ES': 'Gestión de Categorías', 'fr-FR': 'Gestion des Catégories' },
  fixedTransactionsExplanation: { 
    'pt-BR': 'Os seus Ganhos Brutos por mês devem ser de no mínimo', 
    'en-US': 'Your gross monthly earnings must be at least', 
    'es-ES': 'Tus ingresos brutos mensuales deben ser de al menos', 
    'fr-FR': 'Vos gains mensuels bruts doivent être d\'au moins' 
  },
  fixedTransactionsExplanationSuffix: { 
    'pt-BR': 'para cobrir os seus gastos fixos', 
    'en-US': 'to cover your fixed expenses', 
    'es-ES': 'para cubrir sus gastos fijos', 
    'fr-FR': 'pour couvrir vos dépenses fixes' 
  },
  observation: { 'pt-BR': 'Observação', 'en-US': 'Observation', 'es-ES': 'Observación', 'fr-FR': 'Observation' },
  createFixedCategory: { 'pt-BR': 'Criar Categoria Fixa', 'en-US': 'Create Fixed Category', 'es-ES': 'Crear Categoría Fija', 'fr-FR': 'Créer une Catégorie Fixe' },
  editFixedCategory: { 'pt-BR': 'Editar Categoria Fixa', 'en-US': 'Edit Fixed Category', 'es-ES': 'Editar Categoría Fija', 'fr-FR': 'Modifier la Catégorie Fixe' },
  fixedCategoryAlreadyExists: { 'pt-BR': 'Uma categoria com este nome já existe.', 'en-US': 'A category with this name already exists.', 'es-ES': 'Ya existe una categoría con este nombre.', 'fr-FR': 'Une catégorie portant ce nom existe déjà.' },
  fixedExamplesTitle: { 'pt-BR': 'Sugestões de Gastos Fixos', 'en-US': 'Fixed Expense Suggestions', 'es-ES': 'Sugerencias de Gastos Fijos', 'fr-FR': 'Suggestions de Dépenses Fixes' },
  fixedExamplesBody: { 
    'pt-BR': 'Se você tem veículo próprio, considere: Licenciamento, Seguro e IPVA. Se o veículo é alugado: Aluguel do Veículo ou Assinatura. Estes são apenas exemplos para ajudar você a começar!', 
    'en-US': 'If you own your vehicle, consider: Licensing, Insurance, and Taxes. If the vehicle is rented: Vehicle Rent or Subscription. These are just examples to help you get started!', 
    'es-ES': 'Si tienes vehículo propio, considera: Licencia, Seguro e Impuestos. Si el vehículo es alquilado: Alquiler de Vehículo o Suscripción. ¡Estos son solo ejemplos para ayudarte a comenzar!', 
    'fr-FR': 'Si vous possédez votre véhicule, considérez : Licence, Assurance et Taxes. Si le véhicule est loué : Location de Véhicule ou Abonnement. Ce ne sont que des exemples pour vous aider à démarrer !' 
  },
  fixedExamplesNote: { 'pt-BR': 'Cada pessoa conhece seus próprios gastos, ajuste como preferir.', 'en-US': 'Everyone knows their own expenses, adjust as you prefer.', 'es-ES': 'Cada persona conoce sus propios gastos, ajústelos como prefiera.', 'fr-FR': 'Chacun connaît ses propres dépenses, ajustez-les comme vous le souhaitez.' },
  fuelLevelIndicator: { 'pt-BR': 'Indicador de Nível', 'en-US': 'Fuel Level Indicator', 'es-ES': 'Indicador de nivel', 'fr-FR': 'Indicateur de niveau' },
  estimatedLiters: { 'pt-BR': 'Litros Estimados', 'en-US': 'Estimated Liters', 'es-ES': 'Litros estimados', 'fr-FR': 'Litres estimés' },
  max: { 'pt-BR': 'Máx', 'en-US': 'Max', 'es-ES': 'Máx', 'fr-FR': 'Max' },
  budgetLimit: { 'pt-BR': 'Teto de Gasto', 'en-US': 'Budget Limit', 'es-ES': 'Límite de Gasto', 'fr-FR': 'Limite de Dépense' },
  budget: { 'pt-BR': 'Orçamento', 'en-US': 'Budget', 'es-ES': 'Presupuesto', 'fr-FR': 'Budget' },
  noLimit: { 'pt-BR': 'Sem limite definido', 'en-US': 'No limit defined', 'es-ES': 'Sin límite definido', 'fr-FR': 'Pas de limite définie' },
  budgetStatus: { 'pt-BR': 'Status do Orçamento', 'en-US': 'Budget Status', 'es-ES': 'Estado del Presupuesto', 'fr-FR': 'Statut du Budget' },
  budgetRemaining: { 'pt-BR': 'Disponível', 'en-US': 'Remaining', 'es-ES': 'Disponible', 'fr-FR': 'Disponible' },
  budgetExceeded: { 'pt-BR': 'Excedido em', 'en-US': 'Exceeded by', 'es-ES': 'Excedido en', 'fr-FR': 'Dépassé de' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt-BR');

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
